### ISSUE TITLE
Include dist folder into next release

### ISSUE THREAD

**Issue by finn-matti** [akosbalasko/yarle#106]
In order to use yarle as a command without building it first, we need to include the dist folder.

**Comment by akosbalasko** [comment]
But what if we build it in Mac and they try to use it on Windows?

**Comment by akosbalasko** [comment]
We have to think about platform-dependent packages to be published as release, or having a Docker image.

**Comment by finn-matti** [comment]
Is this actually a problem for yarle. What is done differently for Windows?

**Comment by akosbalasko** [comment]
@finn-matti node-gyp rebuild is executed during npm i hence, we have a 3rd party dep. afaik the xml parser which is a wrapper of an c++ code which must be rebuild in the target platform. 

How about this: https://github.com/vercel/pkg
it looks promising as I see. Do you have experience about this?

**Comment by finn-matti** [comment]
But node-gyp is not yarle. Yarle's code itself is not platform dependent, as far as I can see. When installing the package any required packages will just be installed on top.

**Comment by akosbalasko** [comment]
but in yarle's dist folder we have to have a package which is compiled by node-gyp. So what is not really clear for me is how would does this work on windows, if we already ship the dist folder within the release?

**Comment by finn-matti** [comment]
Well, any packages referenced in package.json will also be installed (globally if needed). Look for example at [node-sass](https://github.com/sass/node-sass). This package also needs `node-gyp`, but you can use it with `npx` and install it globally with `npm i -g`.

Try it out (on windows or unix): `npx node-sass --help`.

**Comment by akosbalasko** [comment]
Aham, okay, but node-sass releases pre-builds: https://github.com/sass/node-sass/releases . 
So here they compile the app on different platforms, and npx will use these according to which platform its executed on. 
Another options what I see are:
 1. try to replace xml-stream dep. to a native one (I did not find any native handy/ usable xml streamer package with good performance)
 2. contribute to/fork xml-stream and provide platform-dependent releases from it, with this `npm i ` should work as it is
 3. to have an electron layer on top of yarle,
 4. build platform-dependent releases using github actions
 5. have a Docker image

**Comment by akosbalasko** [comment]
Let me have a try with xml-flow, sounds really promising: https://github.com/matthewmatician/xml-flow

**Comment by akosbalasko** [comment]
@finn-matti wow, stress tests passed. So it looks working. :) I'll push a new release without xml-parser and with dist folder, I think from now we are platform-independent! Thank you so much!

**Comment by akosbalasko** [comment]
@finn-matti , it's out there. Looks fine. Thanks for your contribution!

**Comment by akosbalasko** [comment]
oops, not yet. but anyway, I'm on it. 👍

**Comment by finn-matti** [comment]
Alright. The other option would have been to include a [binding.gyp](https://github.com/nodejs/node-gyp#the-bindinggyp-file) file, it seems.
