### ISSUE TITLE
metadata-block and tags-block not being replaced

### ISSUE THREAD

**Issue by Cito** [akosbalasko/yarle#114]
When converting with the default or sample template, the metadata-block and the tags-block are not properly interpreted for me.

The metadata-block is copied to the output without being processed (verbatim from the template file), while the tags-block is completely missing in the output.

What could be the reason for this? I am running the lastest version on Windows.

**Comment by dsteinbock** [comment]
I'm experiencing the same thing for the location-block, on MacOS. It appears to happen only when the original Evernote note doesn't have location metadata attached. When a note does have location metadata, the output is correct.

Example output:
```
---
evernote-notebook: test2
created-at: 2020-03-01T12:10:28-08:00
modified-at: 2020-12-09T13:03:55-08:00
{location-block}location: {location}{end-location-block}
tags: #test #test2
---
```

**Comment by Cito** [comment]
The actual issue for me was that I used the old settng `include-metadata` instead of  `isMetadataNeeded` in the config file, because that was listed in the README. Just sent PR #124 to fix this.
