### ISSUE TITLE
Problem with path to template file if running via npx

### ISSUE THREAD

**Issue by Cito** [akosbalasko/yarle#115]
When running yarle with npx, the template file setting will be interpreted as a path relative to the installed npm package, no matter whether it has been specified as an absolute or relative path.

We should be able to use an absolute path here, and a relative path should be interpreted relatively to the current directory when running the command.

**Comment by dsteinbock** [comment]
I'm also experiencing this issue. 

I kept getting an error that my template file couldn’t be found. The error showed that yarle was looking for my template deep inside the .npm directory:
`/Users/dsteinbock/.npm/_npx/47104/lib/node_modules/yarle-evernote-to-md/dist/../ds-template.md`

My workaround was to back out of that directory with the following path in my config file: `"templateFile": "../../../../../../ds-template.md",`

It would be great if it just worked with absolute paths instead. Same for the enex source file, which I had to specify as `"/../../test2.enex"` - which is just confusing.

**Comment by Cito** [comment]
I can confirm that this is fixed for me now, thank you!

**Comment by Cito** [comment]
It's working for me now when I use npm install, but when I use npx, then all files are still searched relative to the installed package.

**Comment by Cito** [comment]
It's working for me now when I use npm install. When I use npx, then all files are still searched relative to the installed packagem but I guess this is just because the package in the npm repository does not yet have this fix.
