### ISSUE TITLE
Preserve letter case in filenames

### ISSUE THREAD

**Issue by dsteinbock** [akosbalasko/yarle#117]
#73 was closed but does not appear to be implemented in the latest build. This is also related to #92 .

Discussion in #73 seemed to suggest that the plan was to preserve the letter case of note titles in outputted filenames, instead of converting to lowercase. But filenames are still lowercase.

In Obsidian (and other apps I presume), we use filenames directly in note text as links, so the letter case is meaningful. Converting to lowercase is a loss of data.

**Comment by akosbalasko** [comment]
implemented in: https://github.com/akosbalasko/yarle/pull/119

**Comment by Cito** [comment]
Thanks, I can confirm that this is working for me now.
