### ISSUE TITLE
Feat: templates 

### ISSUE THREAD

**Issue by akosbalasko** [akosbalasko/yarle#12]
It would be nice to have the feature of templates to the converter, for instance a 'literature note' template known in Zettelkasten, to generate the notes directly on that format.

**Comment by rodbv** [comment]
Hey 
Can you provide a sample for such a template? I'd like to give it a shot
What comes to mind as solution is a file with some placeholders like `{% title %}` and  so on. Yarle could have some out of the box, and the user could provide any file path like `--template mytemplate.tpl`

**Comment by akosbalasko** [comment]
I was thinking on that it would be nice if the user could set the order of root elements within the MD file, yes, a placeholder-solution would be great. A default template could be the following: 

{% title %}

{% text %}

{% metadata %}

 And of course, if any static text is among the placeholders, they should be passed into the note itself.

**Comment by rodbv** [comment]
I've started playing around with this concept, but I soon arrived with a slightly more evolved alternative, which not only determines the order of the blocks but their formatting as well.

For example, the current code always renders a title with a leading # (as in `# Title`) and the metadata (created at, updated  at, location) with leading spaces, but the user may want something different

So what I'm considering doing is something like

```
{title-block}# {title}{end-title-block}

{tags-block}
---
Tag(s): {tags}

---
{end-tags-block}

{content-block}{content}{end-content-block}

{metadata-block}
{created-at-block}    Created at: {created-at}{end-created-at-block}
{updated-at-block}    Updated at: {updated-at}{end-updated-at-block}
{location-block}    Where: {location}{end-location-block}
{end-metadata-block}
```

Thus, the user would be able to changed the words and formatting being used, not only position..for example use `##` for title, use a bullet list for metadata, etc etc

One cool side-effect of such templating is that the user wouldn't need to use some settings like `skipLocation` or `skipTags`, they just need to provide a template without these blocks.

**Comment by akosbalasko** [comment]
It sounds very promising @rodbv , go for it! 
And thank you very much for your effort of course! :)
