### ISSUE TITLE
Render external urls as <url> instead of [url](url)

### ISSUE THREAD

**Issue by nununo** [akosbalasko/yarle#133]
I suggest raw urls (which are not associated to a different text) could be rendered as:
```
<url>
````

Instead of:
```
[url](url)
```

It would result in a much more readable `.md` file. `[url](url)` seems redundant since it will have the same url twice. Unless there is some drawback I'm not aware of.

Thanks,
Nuno

**Comment by Cito** [comment]
Since it seems to be standard Markdown syntax (see the section on [automatic links](https://daringfireball.net/projects/markdown/syntax#autolink)), I think that is a good idea.

**Comment by nununo** [comment]
Thanks @akosbalasko !
