### ISSUE TITLE
Evernote internal links

### ISSUE THREAD

**Issue by akosbalasko** [akosbalasko/yarle#14]
Internal links added in Evernote cannot be supported, because the ids (which are used as links) are not embedded in the enex file.

**Comment by finn-matti** [comment]
...but you do have the note title. Granted, this won't always work, but nonetheless. Have you considered this?

**Comment by akosbalasko** [comment]
You mean that if the title of the link in NoteB referencing to NoteA is NoteA (as it is by default) then it could be recognizable, right? 
Well, I looked like a really hacky workaround, which won't work if the label of the note is changed, therefore I was thinking that it doesn't worth the effort. But, on the other hand, this 'partial' feature could beat Evernote's popup window saying that these links work locally only. :)

**Comment by akosbalasko** [comment]
@finn-matti , the more I consider it, the more I see that it can be implemented easier than I thought before, to support links at least on these restricted conditions. What I don't like about it, is its incompleteness because of the missing Id reference from the exported notes. Anyway, I implemented it, it will be included in the next release.
Thanks for raising my attention to this again! :)

**Comment by finn-matti** [comment]
Wow, nice to hear! That is a great starting point for people with lots of interlinked notes to leave Evernote as they so wish.

**Comment by akosbalasko** [comment]
Great, my impression of interlinking notes in Evernote is not as handy to use it frequently. But yes, if someone has plenty of note links, it can be a huge vendor-lock.

**Comment by akosbalasko** [comment]
@finn-matti , fyi it's out, version 2.5.0.
