### ISSUE TITLE
Empty anchor tags can cause parts of notes to be swallowed

### ISSUE THREAD

**Issue by Cito** [akosbalasko/yarle#140]
I noticed that parts of an Evernote note were swallowed and the word `undefined` output instead.

The note looked essentially like this:
```html
...
<p>somethig something.</p>
<a name="foo"/>
<h3>Foo</h3>
<p>Here is a <a href="http://www.modern.ie/en-US/report">link</a> and some more text.</p>
...
```

The output was something like:
```markdown
somethig something.

undefined

and some more text.
```

So the heading and parts of the second paragraph were missing.

The problem here is obviously the self-closing empty anchor tag. Looks like JSDOM closes it only after the next closing `</a>` tag and everything in between is swallowed.

Update: I have now created PR #141 to fix this.

**Comment by akosbalasko** [comment]
Thank you, I merged it.
