### ISSUE TITLE
Names of some attachments (Excel and Word files at least) are wrong

### ISSUE THREAD

**Issue by nununo** [akosbalasko/yarle#162]
Hello,

`yarle` extracts attachments from Evernote, creates them as files and links them correctly as internal links. But some of them (PDF and images work ok) end up with a long strange extension.

Example:
- `Modos.xls` became `Modos.vnd.ms-excel`
- Word documents also have weird names but I no longer have an example. But it was something around `filename.vns.ms-word`

Even though Obsidian still doesn't support XLS, DOC, etc, I expect these to be supported at some point. So, the notes need to link to the right files.

Thanks!

**Comment by akosbalasko** [comment]
Hi @nununo !

Thanks for reporting this issue, it looks fixed in version 3.5.2 (I was changed the precendency between the file extension within the filename and the mimetype, so if the file has been stored with extension, then the code will use that one, otherwise it checks mimetype)

Cheers,
akos

**Comment by nununo** [comment]
Thank you!
