### ISSUE TITLE
Feat: make resource path configurable

### ISSUE THREAD

**Issue by akosbalasko** [akosbalasko/yarle#164]
@tokeriis : I think attachment should be put in one folder for each enex file rather than separate sub folders for each note. Or at least an option for this would be nice.

**Comment by joaosa** [comment]
I think this would be pretty useful in ensuring coherence for resource storage when integrating yarle's output with GitJournal.

**Comment by akosbalasko** [comment]
Thanks for your contribution @joaosa ! Merged, and released.
