### ISSUE TITLE
GPS Location should be ordered lat long

### ISSUE THREAD

**Issue by grantx2016** [akosbalasko/yarle#171]
Decimal GPS location metadata is normally presented as latitude, longitude.

My converted files are showing it in the order longitude, latitude. This is likely to cause issues with any application that ingests that data (e.g. Google maps returns an error).

(BTW, I really appreciate the work you are putting into this. I am currently testing and will have some more feedback in the coming days which I hope helps 👍).

**Comment by akosbalasko** [comment]
Hi @grantx2016 !
Thanks for testing yarle. What a simple mistake from me... sorry about this, I release a fix soon, together with some changes in the config.

**Comment by akosbalasko** [comment]
I released the fix (3.7.0), thanks for raising the issue! And sure, any feedbacks are very welcome.

**Comment by grantx2016** [comment]
Great. Thanks @akosbalasko.
