### ISSUE TITLE
bug: block placeholders and content placeholders work only once

### ISSUE THREAD

**Issue by nikiluk** [akosbalasko/yarle#173]
First, thanks a lot for this great tool @akosbalasko. I don't know what would I do without it if I'd need to move and tag all my notes manually... 

I've noticed the following issue during the conversion. If the template needs to enclose the content placeholders several times, the placeholders work only once and are then treated like a regular text...

**Here is the example template:**
```
---
{metadata-block}
{created-at-block}created: {created-at}{end-created-at-block}
{updated-at-block}modified: {updated-at}{end-updated-at-block}
{end-metadata-block}
---

{title-block}# {title}{end-title-block}

{metadata-block}
{tags-block}> Tags: {tags}{end-tags-block}
{created-at-block}> created: {created-at}{end-created-at-block}
{updated-at-block}> modified: {updated-at}{end-updated-at-block}
{source-url-block}> url: {source-url}{end-source-url-block}
{location-block}> Where: {location}{end-location-block}
{end-metadata-block}
---

{content-block}{content}{end-content-block}
````
**Here's the output:**
![2021-01-09 21 21 45 Quitting evernote md - Visual  (1)](https://user-images.githubusercontent.com/6605974/104106903-6fa23800-52c1-11eb-8559-8a91892308cf.png)

**Comment by grantx2016** [comment]
+1

I've experienced the same behaviour too. I want the tags in the front matter at the top and also at the bottom but discovered that the tags blocks at the bottom just get ignored.

**Comment by akosbalasko** [comment]
Hi @nikiluk , @grantx2016 , 

okay, this looks a real requirement from the tool, and you're right, it handles only one metadata section only. 
No worries, I'll implement the way to replace all placeholders as soon as possible. Probably today. 
thank you for your issues raised, if you satisfied with the tool, may I ask you to give a star for it? :)
It would give more publicity in github.

**Comment by akosbalasko** [comment]
Hi guys, @nikiluk @grantx2016 ,

I implemented it in v3.8.0, please check it.

**Comment by grantx2016** [comment]
Thanks. I confirm it works for Created, Updated and Notebook blocks but does not appear to work for the tags block.

**Comment by akosbalasko** [comment]
You mean that tags are not replaced in both of the places, or none of them?

**Comment by akosbalasko** [comment]
get it, sorry, fix it asap.

**Comment by grantx2016** [comment]
Clarifying that it only updates the tags in the first block.

**Comment by akosbalasko** [comment]
Thank you, it looks to be fixed now.

**Comment by grantx2016** [comment]
Yes, the tags are now entered. Thanks.

However, and unfortunately, it appears that Obsidian requires the tags to be entered without a hash when including in the front matter section and with a hash if they are entered into the body, in order for the tags to be recognized. That would need to be a future feature enhancement for Yarle. In the meantime. I think it is probably possible to workaround with some command line regex.

**Comment by akosbalasko** [comment]
Thanks for the feedback. I'm not sure if its just a bug in Obsidian that can be resolved soon, or a real long-term solution, but let me create a story about the place-dependent tag-settings.
