### ISSUE TITLE
outputDir key should accept an absolute path

### ISSUE THREAD

**Issue by luckman212** [akosbalasko/yarle#187]
Related to #186 

Seems that `outputDir` in the json config only accepts (and thus creates) relative paths. So whatever dir you're in when you invoke YARLE is where the markdown files get created.

Maybe I am misunderstanding or mis-using the tool, but I would like to be able to invoke it from various different directories and have a predictable destination output folder.

**Comment by akosbalasko** [comment]
Hi @luckman212 !
I don't really see the reason why you want to invoke the tool from various folders, could you please explain it a bit?

**Comment by luckman212** [comment]
ok here's an example:

I am currently in the process of moving over 10,000 notes from Evernote to Obsidian. I am trying to do it carefully in smaller batches, so I wanted to set up a repeatable, reliable way to import my enex.

With the current setup, let's say I happen to be in Terminal already, inside a git repo.  If I run the tool, all of a sudden the converted notes are dumped into my project folder.

I think it would make more sense for Yarle to accept absolute paths for all of its parameters. A relative path could still be specified - e.g. if the path doesn't start with a `/` then treat it as a relative path. This is how "most" programs work.

**Comment by akosbalasko** [comment]
But why the option to specify output folder as absolute path would solve your problem? The problem is that you should rewrite the config file to match to the target desktop path because you changed your folder from where Yarle is invoked? Why don't you keep all of your enex files within one folder?

**Comment by luckman212** [comment]
Yes I do export all enex to a single folder (called `yarle-import`)

No matter what dir I'm in when I invoke the tool, I would like the input / output folder to stay consistent.

**Comment by akosbalasko** [comment]
Implemented in v3.9.1
