### ISSUE TITLE
Feature: save tags in .md file's metadata as well

### ISSUE THREAD

**Issue by akosbalasko** [akosbalasko/yarle#19]
It's going to be a MacOnly feature

**Comment by akosbalasko** [comment]
Can be solved relatively easily for Mac, so that's going to be a MacOnly feature.

**Comment by Cito** [comment]
There could be an option to save tags in the Markdown document as "frontmatter", as supported by Obsidian for example.

The syntax is (this must be inserted at the very top of the file):
```
---
tags: tag1, tag2, tag3
---
````

**Comment by joaosa** [comment]
> There could be an option to save tags in the Markdown document as "frontmatter", as supported by Obsidian for example.
> 
> The syntax is (this must be inserted at the very top of the file):
> 
> ```
> ---
> tags: tag1, tag2, tag3
> ---
> ```

Isn't this supported already if one changes the base template? :)

**Comment by Cito** [comment]
@joaosa. Yes, this should be possible. Unfortunately, I cannot test it because of #114 and #115.

I also fear that the tags will appear with `#` characters. But when using the syntax above, the tags must be specified without the `#`. Maybe #96 can solve this.

**Comment by Cito** [comment]
Submitted PR #126 as a possible solution.

**Comment by akosbalasko** [comment]
It's released in v 3.2.1
