### ISSUE TITLE
Preserving indents and consecutive newlines

### ISSUE THREAD

**Issue by daeh** [akosbalasko/yarle#201]
This is a really great project. Thanks so much for making this. 

I'm curious about the feasibility of preserving the whitespace features in evernote files. 

I made heavy use of indents and consecutive line breaks in evernote. Would it be possible to preserve the whitespace features of the `CDATA`? It shouldn't cause any problems for StandardMD editors but would allow editors like Typora to use the information.

E.g. when Yarle processes this `CDATA` code:
```html
<div>line 1</div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div>line 5</div>
<div><br /></div>
<div><br /></div>
<div>level 1</div>
<div style="padding-left:40px;">level 2</div>
<div style="padding-left:80px;">level 3</div>
<div style="padding-left:40px;">level 2</div>
```

it currently generates this markdown:
```
line 1

line 5

level 1
level 2
level 3
level 2
```

whereas it would be _fantastic_ if Yarle generated this instead:
```
line 1



line 5


level 1
	level 2
		level 3
	level 2
```

Does this seem like a possible enhancement?

**Comment by akosbalasko** [comment]
Hi @daeh !

Thank you for reaching this up, it sounds an absolutely meaningful request! 
I think it could be handled by Yarle, I'll investigate it deeper soon (today or tomorrow), and keep you posted about the outcome. If it's positive, i'm glad to implement it too. 

Cheers,
akos

**Comment by akosbalasko** [comment]
Hi @daeh ,

I released a new version(3.12.0) with the fix. indents should be working properly as expected, newline characters are configurable, please set ```keepOriginalAmountOfNewlines``` property to true in your config.json to activate it.

Any feedbacks are welcome!

**Comment by daeh** [comment]
Just playing with it quickly, it looks like if there are multiple new lines at the start of a file, `<YARLE_NEWLINE_PLACEHOLDER>` is left in the `md`.

e.g.

```md
# Cloning time machine backups

<YARLE_NEWLINE_PLACEHOLDER>
<https://egeek.me/2019/05/25/cloning-timemachine-backup-drive-to-another-disk/>

    Created at: 2020-01-30T16:13:19-05:00
    Updated at: 2020-01-30T16:13:42-05:00


```

is produced from 
```xml
<en-note>
	<div><br /></div>
	<div><br /></div>
	<div><a href="https://egeek.me/2019/05/25/cloning-timemachine-backup-drive-to-another-disk/">https://egeek.me/2019/05/25/cloning-timemachine-backup-drive-to-another-disk/</a></div>
	<div><br /></div>
</en-note>
```

**Comment by akosbalasko** [comment]
oh... okay, I don't really know what happened, i tested it and it worked correctly. Now I improved a bit on it, may I ask you to try again?

**Comment by daeh** [comment]
The place holder tag is gone, but it's stripping out the new lines too (even more than normal):

```xml
<div><br /></div>
<div><br /></div>
<div>######</div>
<div>line 1</div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div>line 5</div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div>level 1</div>
```

With `"keepOriginalAmountOfNewlines": false,`
```md
######
line 1

line 5

level 1
		level 2
				level 3
```

With `"keepOriginalAmountOfNewlines": true,`
```md
######
line 1
line 5
level 1
		level 2
				level 3
```

**Comment by akosbalasko** [comment]
Hi @daeh , 
yes, that would be one option, in this case please note that other non-empty divs are going to be converted as a 'paragraph' so, a newline will be added next of them. Hence, it means that instead of the proper amount of newlines, one extra newline will be added. 
Hope it's good enough for you, I released a new version, so you can try it immediately. 
PS: thanks for the other bug report :)
