### ISSUE TITLE
Example .enex file which will not convert

### ISSUE THREAD

**Issue by seatrout** [akosbalasko/yarle#203]
This is a a note, exported as a single enex file, which make Yarle hang completely when it appears in the context of a much larger (4,000 + note) .enex file. 

I offer it as a an aid to debugging. Github won't accept .enex uploads, so I zipped this note. 

[bust enex note.zip](https://github.com/akosbalasko/yarle/files/6137592/bust.enex.note.zip)

**Comment by akosbalasko** [comment]
Hi @seatrout ,

Thank you for sending me this note, I investigate it and try to resolve the issue asap.

**Comment by seatrout** [comment]
I see that an earlier report of this problem got stuck when I failed to press the right button; I didn't think then that I could isolate the note that was causing problems, but the one I have sent you is the one immediately after the last successfully processed note when they are sorted by title ascending, which seems to be how yarle is consuming them.

**Comment by akosbalasko** [comment]
Hi @seatrout , 
That's okay, I was able to reproduce the problem, and I think I have a workaround to make it work. 
Could you please send me your mail address (just write a mail :) ) to let me show the results? I would paste your note directly here. 
Here is my email address: akos0215@gmail.com

Thank you
