### ISSUE TITLE
running as specified in README uses 100% cpu does nothing

### ISSUE THREAD

**Issue by sedlund** [akosbalasko/yarle#210]
Ubuntu 20.10

```
apt install -y node npm
npx -p yarle-evernote-to-md@latest yarle --configFile config.json
```
no tty or files output.  htop shows one `node` process using 100% forever.

` npx -p yarle-evernote-to-md@latest yarle`

no tty or files output.  htop shows one `node` process using 100% forever.

Tried docker:
```
docker run -it --rm -v $PWD:/mnt node bash

root@273d159ee63d:/mnt# npx -p yarle-evernote-to-md@latest yarle --configFile ./config.json
Need to install the following packages:
  yarle-evernote-to-md@latest
Ok to proceed? (y) y
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
sh: 1: yarle: Permission denied
npm notice
npm notice New patch version of npm available! 7.6.0 -> 7.6.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.3
npm notice Run npm install -g npm@7.6.3 to update!
npm notice
root@5ca5ffe17afb:/mnt# npm install -g npm@7.6.3

changed 14 packages, and audited 254 packages in 2s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New patch version of npm available! 7.6.0 -> 7.6.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.3
npm notice Run npm install -g npm@7.6.3 to update!
npm notice
root@5ca5ffe17afb:/mnt# npx -p yarle-evernote-to-md@latest yarle --configFile ./config.json
sh: 1: yarle: Permission denied
```

**Comment by akosbalasko** [comment]
Hi @sedlund , 
could you please share the config.json?
and the node version please. 

thanks.

**Comment by sedlund** [comment]
@akosbalasko 

``` json
{
    "enexSource": "./Inbox.enex",
    "templateFile": "./sampleTemplate.tmpl",
    "outputDir": "./notes",
    "isZettelkastenNeeded": false,
    "plainTextNotesOnly": false,
    "skipWebClips": false,
    "useHashTags": true,
    "outputFormat": "StandardMD",
    "urlEncodeFileNamesAndLinks": false,
    "skipEnexFileNameFromOutputPath": false,
    "haveEnexLevelResources": false,
    "monospaceIsCodeBlock": false,
    "keepMDCharactersOfENNotes": false,
    "keepOriginalAmountOfNewlines": false,

    "nestedTags": {
      "separatorInEN": "_",
      "replaceSeparatorWith": "/",
      "replaceSpaceWith": "-"
   }
}
```

Node on Ubuntu 20.10 is v12.18.2 / npm 6.14.8
Node in docker node:latest is v15.11.0 / npm 7.6.0

**Comment by akosbalasko** [comment]
Could you please try to specify `enexSource` and `templateFile` properties as absolute paths, as it is described in the Readme?  It's just a tip, but it may resolve the issue.

**Comment by akosbalasko** [comment]
Hi @sedlund , 
Sure sure there should be a plenty of output there during the conversion. 
Do you see any logs? like 
⸨░░░⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠴ fetchMetadata: sill resolveWithNewModule ansi-regex@2.1.1 checking installable

and such things? This is the log of downloading the required packages, so if you don't see these kind of logs, it seems to be something hangs around npx. Are you a regular user or a root?

**Comment by sedlund** [comment]
@akosbalasko 

Yes I see the output of npx checking the packages, but nothing directly from yarle.

**Comment by akosbalasko** [comment]
Wow, that's superstrange then, I've never faced anything similar to this.
Could you try one of the test enex files that you can find in the test folder? For instance this: https://github.com/akosbalasko/yarle/blob/master/test/data/test-justText.enex

**Comment by sedlund** [comment]
@akosbalasko 

Same issue.  Just hangs 100% cpu.  Should there be any output if I do not specify --configFile or any options?

If I run it as:

`npx -p yarle-evernote-to-md@latest yarle`

It also just hangs 100% cpu.

**Comment by akosbalasko** [comment]
@sedlund ,
Yes, it should print the location from where the default config is loading:
Loading config from <and the location>.

It strange, because here in github I use actions for CI/CD and they run in Ubuntu 20x. and I have a config for Node12 as well, and it works fine there. 

May I ask you to try to build it directly instead of executing it using npx?

**Comment by akosbalasko** [comment]
@sedlund your Docker log shows that yarle has a permission problem, so it was not executed at all. Could you try to set permissions, or execute it from a user folder?

**Comment by akosbalasko** [comment]
@sedlund I found an other report about the same issue: https://github.com/akosbalasko/yarle/discussions/175
Unfortunately no root cause, he mentioned that he tried on a different machine, and it worked there.  Maybe it's an Ubuntu-specific problem, as he has Ubuntu as I see too?
Can you try it on a different OS?

**Comment by sedlund** [comment]
Ok.  I have learned way more about npm than I ever set out for.

But after changing ~/node_modules/.bin/jarle to just:

> /usr/bin/node --max-old-space-size=1024 ~/node_modules/yarle-evernote-to-md/dist/dropTheRope.js $@

It works.

```
Finished conversion: Wed Mar 17 2021 19:58:42 GMT+0000 (Greenwich Mean Time)

Notes processed: 447

==========================
Conversion finished: 447 succeeded, 0 skipped, 0 failed. Total notes: 447
```

There is something in the startup script that npm installs that causes the hang.

**Comment by akosbalasko** [comment]
Wow, you're great! Thanks for sharing this info! 
So, yes, I'll look around whether these kind of issues raised around npx. Especially for Ubuntu. 

I'm glad you have converted your notes successfully!
And thanks for using Yarle to do it!

**Comment by sedlund** [comment]
I can reproduce the problem in the node docker image (based on Alpine, Ubuntu Buster, and Debian Stretch)) with these files

>Dockerfile
``` dockerfile
FROM node:12-stretch
#FROM node:12-alpine
#FROM node:12-buster

USER node
WORKDIR /home/node
ENV PATH=$PATH:~/node_modules/.bin

RUN npm set unsafe-perm true
RUN npm install yarle-evernote-to-md@latest

COPY ["start.sh", "/home/node"]
ENTRYPOINT [""]
CMD ["/home/node/start.sh"]
```

> start.sh
``` bash
#!/bin/sh

./node_modules/.bin/yarle &

while sleep 1; do
    ps auxwww | grep yarle | grep -v grep
done
```

```
docker build -t yarle .
docker run -it --rm jarle
```

It runs jarle in the background and loops over `ps` output showing it hanging.  I've run this on a AMD64 Ubuntu 20.10 host (the one from above) and also on a Raspberry Pi running Raspbian as a docker host.

**Comment by akosbalasko** [comment]
@sedlund ,
Thanks for the dockerfile and start script, I was able to reproduce the issue as well. 
What I found is this: my start script is the following: 

```javascript
#!/usr/bin/env node --max-old-space-size=1024
/* istanbul ignore file */
// tslint:disable:no-console

import * as dropTheRopeRunner from './dropTheRopeRunner';

dropTheRopeRunner.run({});
// tslint:enable:no-console
```

and if I remove the space-size setting console parameter after node, its runs as expected. If it's there, it hangs. I'll investigate the possible solutions further.

Thank you very much for your effort, you helped a lot, it would not have been done without you.
