### ISSUE TITLE
 node-pre-gyp: Permission denied

### ISSUE THREAD

**Issue by hcguersoy** [akosbalasko/yarle#219]
Trying to run Yarle in a docker container, running in a permission error.
This is strange as the process runs as root.

```
docker run --rm -it -v "$(pwd):/evernote" node:10.22.1-buster-slim bash  
root@27b7eaa842af:/# npx -p yarle-evernote-to-md@latest yarle --configFile /evernote/config.json
sh: 1: node-pre-gyp: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! utimes@4.0.3 install: `node-pre-gyp install --fallback-to-build && node-gyp clean`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the utimes@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-24T13_57_32_371Z-debug.log
Install for yarle-evernote-to-md@latest failed with code 1
```

Tried it with older releases instead of `@latest`, tried installing node-gyp before calling yarle and with node 10.24.0.

**Comment by akosbalasko** [comment]
Hi @hcguersoy !

Could you pls try something proposed here? https://stackoverflow.com/questions/44633419/no-access-permission-error-with-npm-global-install-on-docker-image

**Comment by hcguersoy** [comment]
Hey @akosbalasko,

yeah, starting the container with `--user node` helped. Strange but true ;-)
Thanks for the hint, closing this issue.
