### ISSUE TITLE
'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Cuillerechan** [akosbalasko/yarle#220]
Hi!
Context:

- I know nothing of node.js (like, the first time I copied the line of command, I kept the "<" around the address for the config file, This is my very first time using node.js)
- I'm on Windows

EDIT: I've understand (I think) a bit more and I think I've mostly disrupted things by using npm and npx. So, after I've deleted everything. I've tried these new steps:

- took the config file from the readme and adjusted it (put the right path, chose my options and deleted the template line)
- ran Node.js command prompt
- Ran
>npx -p yarle-evernote-to-md@latest yarle --configFile config.json

And I still get that one and only message: "The system cannot find the path specified." :/
I'm probably missing something but can't understand what.

I've tried copying the default template in a default-template.ts file and link that in the config file, but it doesn't work either.

Old version
----

Steps I've taken:
- downloaded the latest release (3.12.4d) and unzipped it
- completed the config file with my infos
- installed Node.js
- Run the node.js command prompt
- cd "path to the unzipped yarle folder"
- npm i (got errors and warnings)
- npm run build (got errors)
- npx -p yarle-evernote-to-md@latest yarle --configFile /config.json (got a message "The system cannot find the path specified")

I've run that last one multiple times with different config parameters and with an absolute path to config, but I always get the same message)

When I run "npm i", here's what I get:

```
> execSync@1.0.2 install C:\Users\cuill\Downloads\yarle-3.12.4d\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.

> utimes@4.0.3 install C:\Users\cuill\Downloads\yarle-3.12.4d\node_modules\utimes
> node-pre-gyp install --fallback-to-build && node-gyp clean

node-pre-gyp WARN Using request for node-pre-gyp https download
[utimes] Success: "C:\Users\cuill\Downloads\yarle-3.12.4d\node_modules\utimes\lib\binding\Release\node-v83-win32-x64\utimes.node" is installed via remote

C:\Users\cuill\Downloads\yarle-3.12.4d\node_modules\utimes>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" clean )

> fast-xml-parser@3.12.5 postinstall C:\Users\cuill\Downloads\yarle-3.12.4d\node_modules\fast-xml-parser
> node tasks/postinstall.js

              Donating to an open source project is more affordable

                  *** Thank you for using fast-xml-parser! ***

                 Please consider donating to our open collective
                      to help us maintain this package.

                https://opencollective.com/fast-xml-parser/donate
                                      or
                   https://www.patreon.com/bePatron?u=9531404
                                      or
   https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KQJAX48SPUKNC

                                     ***



> nodemon@2.0.5 postinstall C:\Users\cuill\Downloads\yarle-3.12.4d\node_modules\nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 541 packages from 1219 contributors and audited 545 packages in 18.216s

18 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

and when I run "npm run build", I get this:

```
> yarle-evernote-to-md@3.12.4-d build C:\Users\cuill\Downloads\yarle-3.12.4d
> npm run clean && npm i  && tsc --project ./src/tsconfig.json


> yarle-evernote-to-md@3.12.4-d clean C:\Users\cuill\Downloads\yarle-3.12.4d
> rm -f -r ./out && rm -f -r ./dist && rm -r -f ./node_modules

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yarle-evernote-to-md@3.12.4-d clean: `rm -f -r ./out && rm -f -r ./dist && rm -r -f ./node_modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yarle-evernote-to-md@3.12.4-d clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cuill\AppData\Roaming\npm-cache\_logs\2021-03-25T15_22_18_801Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yarle-evernote-to-md@3.12.4-d build: `npm run clean && npm i  && tsc --project ./src/tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yarle-evernote-to-md@3.12.4-d build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cuill\AppData\Roaming\npm-cache\_logs\2021-03-25T15_22_18_839Z-debug.log
```

You'll find attached the two logs mentioned here.
[2021-03-25T15_22_18_839Z-debug.log](https://github.com/akosbalasko/yarle/files/6205947/2021-03-25T15_22_18_839Z-debug.log)
[2021-03-25T15_22_18_801Z-debug.log](https://github.com/akosbalasko/yarle/files/6205948/2021-03-25T15_22_18_801Z-debug.log)

Does anyone know what I'm missing for this to work? Have I done something wrong in the config file? (I couldn't find all the same parameters that are described in the readme and found some there that are not described but I don't think this should change much...)

**Comment by akosbalasko** [comment]
Hi @Cuillerechan !

It looks like that this comment provides a solution: https://github.com/imagemin/imagemin/issues/199#issuecomment-324735995

Thanks for raising this up, I realized that I missed to set the latest version to released here, so the latest one is 3.12.5.

**Comment by Cuillerechan** [comment]
Well, the comment in question is really not clear to me, but here is what I tried:

- Run
>npx -p yarle-evernote-to-md@3.12.5 yarle --configFile config.json
that gave me the same message
>npx config set script-shell bash
said config is not a command
>npx --shell bash -p yarle-evernote-to-md@3.12.5 yarle --configFile config.json
this time yarle is the command it couldn't find 🤷 

I'm not sure what else to try. Should I do the npm version? From what I understand this version requires installation, right?

**Comment by akosbalasko** [comment]
Hi @Cuillerechan !

Run `npm config set script-shell bash` , not `npx config set script-shell bash`, npm and npx are different apps. And then try `npx -p yarle-evernote-to-md@3.12.5 yarle --configFile config.json` in the folder where your config.json is located.

**Comment by Cuillerechan** [comment]
Oh, ok. Since they are different apps, I thought setting a configuration for one wouldn't change anything on the other ^^'


I have a different thing!! :)
It's not yet just the expected result, but that a great advance!

now it says
```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn bash
npm ERR! file bash
npm ERR! path bash
npm ERR! errno -4058
npm ERR! utimes@4.0.3 install: `node-pre-gyp install --fallback-to-build && node-gyp clean`
npm ERR! spawn bash ENOENT
npm ERR!
npm ERR! Failed at the utimes@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cuill\AppData\Roaming\npm-cache\_logs\2021-03-25T20_45_02_629Z-debug.log
Install for [ 'yarle-evernote-to-md@3.12.5' ] failed with code 4294963238
```

I'll attach the log too. Thank you so much for your continuous help!
[2021-03-25T20_45_02_629Z-debug.log](https://github.com/akosbalasko/yarle/files/6207776/2021-03-25T20_45_02_629Z-debug.log)

**Comment by akosbalasko** [comment]
Welcome, sorry for havin difficulties with the installation, it should not happen. 

Oh, okay, if I understand well, an external package requires to be rebuilt natively on Windows. May I ask the version of it? Windows 10 maybe? 
It should not happen by the way, I'll contact with the developers to provide a solution for this, but as a workaround I think this command should solve the issue: `npm install -g windows-build-tools`

Thank you!

**Comment by Cuillerechan** [comment]
Yes, it is windows 10 indeed.

This command gave me another set of errors
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> windows-build-tools@5.2.2 postinstall C:\Users\cuill\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn bash
npm ERR! file bash
npm ERR! path bash
npm ERR! errno -4058
npm ERR! windows-build-tools@5.2.2 postinstall: `node ./dist/index.js`
npm ERR! spawn bash ENOENT
npm ERR!
npm ERR! Failed at the windows-build-tools@5.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cuill\AppData\Roaming\npm-cache\_logs\2021-03-25T21_13_56_058Z-debug.log
```
And the log - just in case:
[2021-03-25T21_13_56_058Z-debug.log](https://github.com/akosbalasko/yarle/files/6207911/2021-03-25T21_13_56_058Z-debug.log)

and the npx command gives me the same error as previously

Yeah, it really is annoying when things should work but somehow they don't. The joy of computers ^^

**Comment by akosbalasko** [comment]
Hi @Cuillerechan ,

I tried to eliminate the root cause, I releassed a new version of Yarle, could you please retry by the command: `npx -p yarle-evernote-to-md@latest yarle --configFile config.json` ? 

Thank you, and sorry for the inconveniences.

**Comment by seatrout** [comment]
I'm having exactly the same problem. As you know, I had it working perfectly well with an earlier version of yarle, but now, with the same config file and everything. I just get "the system cannot find the path specified" and when I specify the shell as "bash" I get the same post-install error.

**Comment by akosbalasko** [comment]
Hi @seatrout , 
Could you please provide some error logs? It looks like that a 3rd party dependency has to be recompiled for Windows 10 (maybe because of an upgrade of an OS). So normally it should be used by downloading a precompiled version that would eliminate all of these compilation issues. I'll contact with the developer of the tool (it is utimes, it is used to get a file's creation date from the OS).

Sorry for the troubles.

**Comment by seatrout** [comment]
here's the most recent log  (and why are so many lines prefixed with "silly"?
[2021-03-28T17_04_46_445Z-debug.log](https://github.com/akosbalasko/yarle/files/6217864/2021-03-28T17_04_46_445Z-debug.log)

**Comment by Cuillerechan** [comment]
Hi, 
I'll be able to check again next week. I'll let you know then how this goes.
Best,
Cuillère

**Comment by akosbalasko** [comment]
Hi @Cuillerechan hi @seatrout ,
Sorry for the delay, I was focusing on the new release of Yarle, which is big one: I released desktop applications for the popular OS-s, just to make these recompilation steps unnecessary. So technically these new version should solve these problems hence I would close this issue, but of course open a new one if you still face some problems.

Feel free to give it a try, the links to the binaries are in the readme.

**Comment by pmottishaw** [comment]
I am having exactly the same error `The system cannot find the path specified.`   using PowerShell on Windows 10 (I also tried on WSL/Ubuntu on the same machine and hit different problems - see my earlier post). 

I do have the new GUI version working, but I would like to be able convert multiple enex files (to preserve links between notes). Either fixing this bug or adding that feature (multiple enex processing) to the GUI would be very much appreciated.

**Comment by akosbalasko** [comment]
Hi @pmottishaw !

I think supporting multiple enex files with link preservasion would be a really great improvement (link preservation was not done by the old version of yarle, I simply forgot the scenario of linkink notes inter-enex, shame on me). Let me create a new issue for it.
