### ISSUE TITLE
With ObsidianMD, PDF linked instead of embedded

### ISSUE THREAD

**Issue by jornetsimon** [akosbalasko/yarle#223]
When using ObsidianMD as output, the images are embedded while the PDFs are linked.
```markdown
# Jeux de société - Sac 2

![[./_resources/Jeux_de_société_-_Sac_2.resources/Attachment.jpg]]
![[./_resources/Jeux_de_société_-_Sac_2.resources/img_20200705_184138.jpg]]
![[./_resources/Jeux_de_société_-_Sac_2.resources/img_20200705_184155.jpg]]
```

```markdown
# Facture octobre 2020
[[./_resources/Facture_ostéo_octobre_2020.1.resources/Facture.pdf | Facture.pdf]]
```

I did not recognize any config option to force it.

**Comment by akosbalasko** [comment]
Hi @jornetsimon , 

I extended the code to generate Obsidian links for attachments also, please execute the command again to check it out. Feel free to reopen the issue, or open a new one if you still have problems with the notes generated.
