### ISSUE TITLE
'npm i', as shown in the README, is not sufficient to install

### ISSUE THREAD

**Issue by upnix** [akosbalasko/yarle#23]
For installation, the README states:  
## Installation

 - [install Node.js](https://nodejs.org/en/download/). Please use Node 10.18.1 because of 3rd party dependencies rebuild problems. 
  
 - clone or download this repo
 - npm i

However, the 'build' directory is never created, leading to subsequent "npm run start" commands to fail.

```npm run build``` appears to fix the issue.

**Comment by akosbalasko** [comment]
Hi @upnix ,

Sorry for the misunderstanding I added this section to make it clear which is the required version of Node. You're right, its just about the installation of the dependencies, not building the code itself. I'll extend the Readme with a build section.
