### ISSUE TITLE
can't run CLI version anymore as of 4.0.0

### ISSUE THREAD

**Issue by luckman212** [akosbalasko/yarle#230]
Hi @akosbalasko - congrats on the new GUI in 4.0 - that looks pretty nice! 🚀 

I prefer the terminal though, and had a nice script / template system already set up and working well with 3.x

Now, with 4.0, I am throwing an error:

```bash
$ npx -p yarle-evernote-to-md@latest yarle --configFile ~/.yarle/config.json
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module '/Users/luke/node_modules/@electron-forge/cli/dist/electron-forge.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

For now, manually invoking the 3.14 version works:
```bash
$ npx -p yarle-evernote-to-md@3.14 yarle --configFile ~/.yarle/config.json
```

my versions:
```bash
$ for c in npx node; do echo "$c: $($c -v)"; done
npx: 7.8.0
node: v15.13.0
```
thank you for any help.

**Comment by akosbalasko** [comment]
hi @luckman212 !

nopenope, currently npx can be used for legacy versions only.
 The problem is that afaik npx and electron uses the same property in package.json, but supporting npx-stylecas well is on my roadmap, so it will be resolved somehow soon.

**Comment by akosbalasko** [comment]
Hi @luckman212 ,
I think I solved it, it was easier to fix than I expected. 
Cheers,
akos

**Comment by luckman212** [comment]
🎉  yes, it works now! brilliant! thank you so much for this great tool.
