### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by abogawat** [akosbalasko/yarle#237]
I'm trying to use the latest version on Windows. The GUI doesn't work, as has already been noted in another issue yesterday. But when I try to use the commandline version, I keep getting an error saying "The system cannot find the path specified."

I've double and triple checked to make sure all the paths (enex and folder path in the config.json, and the config.json path in the command) are correct. No idea what that error is referring to!

**Comment by akosbalasko** [comment]
Hi @abogawat !

I'll release the Windows Gui today, which will resolve this problem. I'll update you when it is ready to be downloaded.

**Comment by abogawat** [comment]
@akosbalasko Awesome! Looking forward to it. Thanks!

**Comment by akosbalasko** [comment]
Hi @abogawat ,
The new version is released, you can download it for Windows from here: https://github.com/akosbalasko/yarle/releases/download/v4.0.3/yarle-evernote-to-md-4.0.3.Setup.exe

If you face with any problems feel free to open a new issue, I would close this one. 

Cheers,
akos

**Comment by abogawat** [comment]
Thanks, @akosbalasko. The new version works just fine.
