### ISSUE TITLE
Exported resources should have their filenames escaped for filesystem compatibility

### ISSUE THREAD

**Issue by SpadarShut** [akosbalasko/yarle#240]
I had some audio recordings in evernote notes, their filemanes contained `:` and files were not written to the filesystem. So embedded resources' filenames need to be escaped.

**Comment by akosbalasko** [comment]
I'm sorry, it was resolved two weeks after: [fix: tests on windows](https://github.com/akosbalasko/yarle/commit/b153ca9857407b095ef8274e0f3c5a7586bccf5d) I just simply forgot to reference it back to this issue.
