### ISSUE TITLE
Tags issue when they have a period in them

### ISSUE THREAD

**Issue by aashish108** [akosbalasko/yarle#247]
Hey there! When exporting tags with periods in them (e.g. Financial.Bills.Whatever), this tag is not recognised in Obsidian unfortunately! It will only show Financial. Is there a way to adjust the tag export so that it replaces the period with an underscore? I thought the options for `Separator of nested tags in EN` and `Replace separator with` would be it but apparently not!

Thanks!

**Comment by akosbalasko** [comment]
Hi @aashish108 !

so, do you mean, that if you set Separator of nested tsgs in EN to a point, and replace separator with to _ , it does not work?

**Comment by aashish108** [comment]
Hey, yeah it doe snot seem. To do anything and I tried many times. Not sure what I'm doing wrong!

--
Aashish Sharma
Full-stack Developer

-------- Original Message --------

**Comment by akosbalasko** [comment]
Aham, and did you try it via UI or via command line? It should work, so probably its a bug there, if I guess well, it will be in the UI, and by using it via command line, it may work properly. 
Anyway, I'll investigate it asap. Thank you for raising this up!

**Comment by akosbalasko** [comment]
hi @aashish108 , 
I caught the bug, it was on the UI. I release a new version, 4.0.6 with a fix. Could you please try again? 
Thank you!

**Comment by aashish108** [comment]
Hey @akosbalasko I tried it again and now the tags is like this:

```
Tags: #___________ #___________
```

I put a dot for `Separator of nested tags in EN` and an underscore for `Replace separator with` and enabled generate nested tags and also add hash to tags.

Cheers!

**Comment by akosbalasko** [comment]
Oh, okay, the problem is the point then, type a backslash before it:  \.
These fields are used as regular expressions where the point is a dedicated character, but with backslash we can state that the point is just a point. 
Sorry, I'll improve the description there.

**Comment by aashish108** [comment]
Brilliant, the tags now works! Thanks for the fix.
