### ISSUE TITLE
Problem with tags

### ISSUE THREAD

**Issue by Vadych** [akosbalasko/yarle#250]
For some reason, I get such a block with tags at the output

Tagged: 
```
#undefinedСundefinedбundefinedыundefinedтundefinedоundefinedвundefinedыundefinedеundefined-undefinedаundefinedкundefinedцundefinedиundefinedиundefined
```

**Comment by akosbalasko** [comment]
Hi @Vadych ,
Could you please share me your conversion.log, especially the log that shows your configuration? 
Thank you.

**Comment by Vadych** [comment]
No problem!
Log and .enex
[log.txt](https://github.com/akosbalasko/yarle/files/6342770/log.txt)
[Evernote.enex.zip](https://github.com/akosbalasko/yarle/files/6342778/Evernote.enex.zip)
Thank you!

**Comment by akosbalasko** [comment]
aham, okay, thank you! 
As a workaround I would suggest to set 

`separator In EN` to \.
`replace Separator With` to .
and `replace Space With` to a whitespace 
and check whether it works correctly. 
Thank you!

**Comment by Vadych** [comment]
Thanks! It helped.
Is it possible to convert tags to the form [[tag1]], [[tag2]]?

**Comment by akosbalasko** [comment]
I'm glad to hear it! 
Nope, unfortunately currently its not supported. But definitely makes sense, let me add it as a feature request. I'll keep you updated about the progress. 
As this issue was about the tags-config, I close this.
