### ISSUE TITLE
Version 4.0.7 don`t create file

### ISSUE THREAD

**Issue by Vadych** [akosbalasko/yarle#253]
After the launch, the following log is output and nothing further happens
Log
`Current config is: {"enexSource":"C:\\Users\\sisin\\Downloads\\Evernote.enex","outputDir":"C:\\Users\\sisin\\Dropbox\\Knowledge\\0Inbox","keepOriginalHtml":false,"isMetadataNeeded":true,"isNotebookNameNeeded":false,"isZettelkastenNeeded":false,"plainTextNotesOnly":false,"skipWebClips":true,"useHashTags":false,"nestedTags":{"separatorInEN":"_","replaceSpaceWith":"-","replaceSeparatorWith":"/"},"outputFormat":"ObsidianMD","urlEncodeFileNamesAndLinks":false,"pathSeparator":"/","skipLocation":true,"skipCreationTime":false,"skipUpdateTime":false,"skipSourceUrl":false,"skipTags":false,"skipEnexFileNameFromOutputPath":false,"keepMDCharactersOfENNotes":false,"monospaceIsCodeBlock":false,"currentTemplate":"This is my template!\n\n{title-block}# {title}{end-title-block}\n\n---\n\n\n\n{content-block}{content}{end-content-block}\n\n---\n\n{created-at-block}_Created at {created-at}._{end-created-at-block}\n{updated-at-block}_Last updated at {updated-at}._{end-updated-at-block}\n{source-url-block}_Source URL: []({source-url})._{end-source-url-block}\n\n\n{tags-block}\nTagged: \n```\n{tags}\n```\n{end-tags-block}\n"}
setting paths
path: C:\Users\sisin\Downloads\Evernote.enex
Current config is: {"enexSource":"C:\\Users\\sisin\\Downloads\\Evernote.enex","outputDir":"C:\\Users\\sisin\\Desktop","keepOriginalHtml":false,"isMetadataNeeded":true,"isNotebookNameNeeded":false,"isZettelkastenNeeded":false,"plainTextNotesOnly":false,"skipWebClips":true,"useHashTags":false,"nestedTags":{"separatorInEN":"_","replaceSpaceWith":"-","replaceSeparatorWith":"/"},"outputFormat":"ObsidianMD","urlEncodeFileNamesAndLinks":false,"pathSeparator":"/","skipLocation":true,"skipCreationTime":false,"skipUpdateTime":false,"skipSourceUrl":false,"skipTags":false,"skipEnexFileNameFromOutputPath":false,"keepMDCharactersOfENNotes":false,"monospaceIsCodeBlock":false,"currentTemplate":"This is my template!\n\n{title-block}# {title}{end-title-block}\n\n---\n\n\n\n{content-block}{content}{end-content-block}\n\n---\n\n{created-at-block}_Created at {created-at}._{end-created-at-block}\n{updated-at-block}_Last updated at {updated-at}._{end-updated-at-block}\n{source-url-block}_Source URL: []({source-url})._{end-source-url-block}\n\n\n{tags-block}\nTagged: \n```\n{tags}\n```\n{end-tags-block}\n"}
setting paths
`

**Comment by akosbalasko** [comment]
Hi @Vadych !
ouch, sorry. Wouldn't you mind to try version 4.0.6?

thank you!

**Comment by akosbalasko** [comment]
Thank you for reporting this, I have to take more care on testing on Windows hence I revoked 4.0.7 release, so the current is 4.0.6.
