### ISSUE TITLE
Desktop App Accumulates Jobs

### ISSUE THREAD

**Issue by grantx2016** [akosbalasko/yarle#257]
Steps to reproduce:
1. Configure a migration job and run it ("Job A")
1. Delete the output
1. Configure another migration job and run it ("Job B")
Expected output: Notes from Job B only
Actual output: Notes from Jobs A and B (ie. It appears to run Job A again, before running Job B, even though only configured for Job B). 

Weird! 🤔
 
Yarle Desktop Version: 4.0.6
macOS: 10.15.7

**Comment by akosbalasko** [comment]
Hi @grantx2016 !
jeah,I realized the same, thanks god it's not about accumulating the jobs, it simply does not clear the logs before the new configuration. 
The weird thing is that i afair unlink the log file.

**Comment by akosbalasko** [comment]
Hi @grantx2016 ,
It's fixed in version 4.0.9, the log file contains info about the current execution only.

**Comment by grantx2016** [comment]
Great. Thanks @akosbalasko . 🕺

**Comment by grantx2016** [comment]
> Hi @grantx2016 ,
> It's fixed in version 4.0.9, the log file contains info about the current execution only.

When using this version, aftering the clearing the log via the UI after the first run, and then re-running, no log is produced.

**Comment by akosbalasko** [comment]
Hi @grantx2016 ,
what do you mean on "clearing the log via UI after the first run"? Did you clear the textarea manually? Or did you close the app and then open it again? Or just left everything as they are, navigated back to step one without closing the app and then did the flow again?

**Comment by grantx2016** [comment]
I cleared the log text in the UI manually, left the app open with the same settings, then re-ran with a different input .enex file. The app appears to run ok but no log is produced this time around.

FYI, I am doing this workflow as I am trying to troubleshoot conversion failures so I am using the same settings but inputting slightly different .enex files to try to locate the troublesome attachment that is causing the failure.

**Comment by akosbalasko** [comment]
ok, okay get it, thanks for the feedback. I tested it by closing-reopening the app, but this scenario does not fit your workfow as the settings are not stored if I'm right. 
Ok, let me check it out. 
Thank you!

**Comment by akosbalasko** [comment]
Ok, I think the easiest way to make it work is to do not remove the logs manually, because it will be updated by the tool. If you don't erase the logs, it works. Tricky, btw :).

To prevent this manual modification of the logs I'll add a feat. to make that text area read only.

**Comment by grantx2016** [comment]
OK. That will work for now. Thanks!
