### ISSUE TITLE
tags filled with "undefined"

### ISSUE THREAD

**Issue by seatrout** [akosbalasko/yarle#258]
Using Yarle 4.06 I have a small, worrying problem: all my evernote tags are written into the markdown metadata with the string "undefined" between every letter. This happens only with tags, Example:

```
---
 tags: undefinedSundefinedwundefinedeundefineddundefinediundefinedsundefinedhundefined undefinedRundefinedeundefinedcundefinediundefinedpundefinedeundefinedsundefined undefinedPundefineduundefineddundefineddundefinediundefinednundefinedgundefinedsundefined_undefinedaundefinednundefineddundefined_undefinedbundefinediundefinedsundefinedcundefineduundefinediundefinedtundefinedsundefined 
---
# English version of the Hazelnut tårta
```

Obviously I can, and do, work around this by running a global find and replace to strip out all the "undefined"s. After that, all the tags appear as they should. But it's an irritating problem. 

I have not tried what happens if I leave the setting to prefix tags with hashmarks, because that is not needed in a metadata block for Obsidian.

**Comment by grantx2016** [comment]
I'm guessing that you have left some the tag config fields empty. Try inserting "" instead. That solved it for me.

**Comment by akosbalasko** [comment]
As I see it has already been resolved by one of the subsequent version by updating the default config with the settings of the nested tags, so they will have default values set even if they had not been set in the UI.
