### ISSUE TITLE
ISO date munged in conversion

### ISSUE THREAD

**Issue by seatrout** [akosbalasko/yarle#259]
WHen I enter "DD-MM-YYYY" as the date format string, the results are very strange: 

```  
      Created at: Su-29-yyyy
     From Evernote: Cooking
```

**Comment by akosbalasko** [comment]
Hi @seatrout ,
Are you sure that you did not mistype it as dd-MM-yyyy or dd-mm-yyyy? Because 'dd' would mean Su as Sunday, MM is the day in the month while yyyy could not be recognized so that would be yyyy . 
Could you please share the logs with me? 
Thank you!
