### ISSUE TITLE
Cannot empty log file

### ISSUE THREAD

**Issue by seatrout** [akosbalasko/yarle#260]
On multiple runs of Yarle 4.04, the log window becomes very cluttered and uninformative. It shows the results of all previous runs before the current one. This is confusing and there seems no way to change it.

**Comment by akosbalasko** [comment]
Hi @seatrout ,
As a workaround you can delete the conversion.log by hand until I release the fix.

**Comment by akosbalasko** [comment]
Fixed in v4.0.9.
