### ISSUE TITLE
configurable _resourceFolder 

### ISSUE THREAD

**Issue by akosbalasko** [akosbalasko/yarle#263]
It would be a cool improvement for Obsidian to make resourceFolder configurable and if (resourceFolder === null && outputFormat === 'ObsidianMD') then format should be ![[file.png]]

**Comment by medmunds** [comment]
Part of this is in PR #279

**Comment by akosbalasko** [comment]
Improvements done in #279 and #284 are for customizing the resource folders' name, not to collect and store all the attachments in one commonplace, which is afair the root request.
