### ISSUE TITLE
Incorrect output if $ encountered

### ISSUE THREAD

**Issue by JimKnecht** [akosbalasko/yarle#272]
Hi, I have some text from websites on command line Mac/Linux commands that are not converting right.  $' is causing some issues. Is there any way to get around that or will I need to edit each note before export?

My Evernote has this:

```
grep 'Price: $' partslist.txt
 # Incorrect: Only matches "Price: " at the end of a line

grep 'Price: \$' partslist.txt
 # Correct: Matches "Price: " followed by a dollar sign 
```

The converted to Obsidian file looks like this:

> grep 'Price: 
> 
> ---
> 
> _Created at 2013-02-22T23:42:37-05:00._
> _Last updated at 2013-02-22T23:44:13-05:00._
> 
> 
> Tagged: 
> ```
> Search
> ```
> 
>  partslist.txt
>  
>  
>  # Incorrect: Only matches "Price: " at the end of a line
> 
>  grep 'Price: \\
> 
> ---
> 
> _Created at 2013-02-22T23:42:37-05:00._
> _Last updated at 2013-02-22T23:44:13-05:00._
> 
> 
> Tagged: 
> ```
> Search
> ```
> 
>  partslist.txt
>  # Correct: Matches "Price: " followed by a dollar sign
>

**Comment by akosbalasko** [comment]
Hi @JimKnecht ,

You can try `keepMDCharactersOfENNotes` property to set to true, it may resolve the problem, but I say this for first sight, I'm not sure. 

And of course, feel free to raise this up again if it doesn't solve the problem, and I'll investigate it in a deeper level.
