### ISSUE TITLE
outputFormat in windows app

### ISSUE THREAD

**Issue by brandon0824** [akosbalasko/yarle#273]
Thanks for your project!
I am using windows client, when I run the software, after changing the outputFormat to StandardMD in Step 2, the converted markdown file is still adapted to Obsidian's [[]] image path, not the normal markdown file ( A format like ![]() )
Would like to ask if there is any solution to this problem?

**Comment by akosbalasko** [comment]
Hi @brandon0824 , 

thank you for reporting this issue, i check it out and provide a solution or a fix soon

**Comment by akosbalasko** [comment]
Hi @brandon0824 ,
I think I found the bug, please try again with the latest version of Yarle(4.0.11).
Thank you for raising my attention to this, it was a silly bug. Sorry.

**Comment by brandon0824** [comment]
Really appreciate it!
