### ISSUE TITLE
Conversion of strikethrough doesn't work with Obsidian or Joplin

### ISSUE THREAD

**Issue by medmunds** [akosbalasko/yarle#282]
[I'm not sure whether this is a bug report or feature request.]

In Yarle 4.0.11, text formatted with ~~strikethrough~~ in Evernote is converted to `~strikethrough~` (by turndown-plugin-gfm). That works in GFM and some other Markdown dialects, but is not supported by Obsidian or Joplin. Both of those require double tildes: `~~strikethrough~~`. (And Joplin actually has an option to treat single tildes as <sub>sub</sub>script.)

I can think of a few potential fixes:

1. Always convert `<s>` (and `<del>` and `<strike>`) to double tilde `~~strikethrough~~`. This would work with Obsidian and Joplin, and would continue to work with GFM (which also supports double tilde).
2. Don't convert `<s>` etc.—just leave the html intact. (That's what CommonMark seems to prefer. And it works with Obsidian, Joplin, and GFM. This would require somehow disabling the `<s>` rule from turndown-plugin-gfm.)
3. Add a new config option for how to convert strikethrough: `~`, `~~`, or leave the html as is.

The first one seems cleanest to me; happy to open a PR for it if you're interested. (I started down the path of the third one, [adding a config option](https://github.com/medmunds/yarle/commit/c394f35362c4f8d857a9531ff14acbf44ac7396a), and could open a PR for that if desired, but it seemed kind of ugly the more I looked at it.)

**Comment by akosbalasko** [comment]
Hi @medmunds ! 
Sure thing, I would vote on version 1, just double the tilde. And yes, of course, thank you for implementing this, I'm glad to merge your PR.

**Comment by medmunds** [comment]
No problem, @akosbalasko ! (And thank you for Yarle!)
