### ISSUE TITLE
EN note with underscore (`_`) in name linked wrong

### ISSUE THREAD

**Issue by hcguersoy** [akosbalasko/yarle#289]
Running the macOS standalone app.

* macOS: 11.5
* Yarle Version: 4.1.0 (4.1.0) 
* EN Version: 10.17.8-mac-mas-public (458743)
* Yarle settings:

- convert webclips
- Perform URL encoding
- keep original newlines
- add 'md' extension
- Monospace as codeblock
- Add # to tag

I've exported two larger notebooks which have many links between the notes. 

Some of the notes have names with an underscore instead of spaces in their names as a word delimiter, e. g.

`note_1020` instead of `note 1020`.

After running Yarle the links to the notes with an underscore are broken because the underscore in the link is doubled, e.g. 

```
[[20200903__building.md\|20200903\_building]] |
```

I've tried both enabling and disabling the setting _Perform URL Encoding on FileNames And Links_.
The document `20200903_building.md` exists!

**Comment by akosbalasko** [comment]
Hi @hcguersoy !
Thank you for reporting this issue, I'll investigate it.

**Comment by pmottishaw** [comment]
I also see this behaviour.
