### ISSUE TITLE
Can not build, error: can not find utime binary

### ISSUE THREAD

**Issue by guoboism** [akosbalasko/yarle#299]
I an trying to build the project. But get error after calling npm start

![image](https://user-images.githubusercontent.com/705499/129613407-ad9fa603-e2cc-4ebc-b88c-617e5ed5474c.png)

**Comment by akosbalasko** [comment]
Hi @guoboism !

Which Node version do you use? Basic question, but the devil and the details, you know: didn't you forget to call "npm i" to install dependencies (including utimes)?

**Comment by akosbalasko** [comment]
Similar issue raised here, please check how it was 
resolved: https://github.com/akosbalasko/yarle/issues/261

**Comment by guoboism** [comment]
> Hi @guoboism !
> 
> Which Node version do you use? Basic question, but the devil and the details, you know: didn't you forget to call "npm i" to install dependencies (including utimes)?

Platform: win10
Node js 16.7.0
Python 3.9.6

I dont have much experience with node.js
I just run
`npm install`
then
`npm start`

Is there anything else to note？

**Comment by guoboism** [comment]
Unfortunately，I still can not build with latest code， with the same error report of utime

Here is shows some warning after npm install, are they the problem?
![Snipaste_2021-08-18_19-04-47](https://user-images.githubusercontent.com/705499/129888203-bbc25d45-49e2-469e-ad18-52152d2abece.png)

**Comment by akosbalasko** [comment]
Hi @guoboism !

If you just would like to use the app, I would suggest to download the precompiled and bundled application instead of compiling it directly.

**Comment by guoboism** [comment]
> Hi @guoboism !
> 
> If you just would like to use the app, I would suggest to download the precompiled and bundled application instead of compiling it directly.

I kind of solved the utimes bug(by changing the binding folder name). But there more errors following(Error: Cannot find module './installers/setupEvents'). 
I guess windows is not your dev environment? 

I want to build because I am trying to convert my evernote notes to logseq, which is in md but in different file structure. Also there are some minor bugs in the app (seperation line replacement not working https://github.com/akosbalasko/yarle/issues/301).

I still hope you can share more on how to build.

**Comment by akosbalasko** [comment]
Well, I don't think that changing the binding folder name could resolve the problem.

I'm not sure what do you mean on 'different file structure' in case of logseq, but if you mean that the content (and the metadata) is placed within an md file differently, you could set up/change the template format in Yarle to fit the one desired by Logseq. In this case please share this with me, I'm thinking on setting up predefined templates for the target note apps like Obsidian or Logseq etc. 

If you still would like to compile the code manually and improve it and then share it with others, first of all, please create a fork about it, then do your changes there and finally open a pull request to the original repo. In this case I can review and merge it into the master code. 
About the correct build: yes, I develop it in Mac, but I set up github actions to test the application on Windows as well. It works well, meaning that the code is compiled well on Windows by the commands described here: https://github.com/akosbalasko/yarle/blob/master/.github/workflows/run-tests-windows.yaml (line 26-28 is interesting for you, and please note that the tests run on Node 10, 12 and 14, not on 16.x)

**Comment by guoboism** [comment]
@akosbalasko Thanks for your help. I changed to node 14.x and run the script in your yaml before npm start and it finally can launch! :joy:

As for Logseq: 
- All attachments and imags should be in /Assets and .md files be in /Pages
- Logseq use block as internal strucrue, so paragraph should start `-` at start of line
- some syntax details are a bit different from standard md

If I can fix the issues above, I sure will submit so that yarle will be a comprehensive evernote-md importer.

**Comment by scpedicini** [comment]
Just to add to this, I couldn't build using ARM versions of node 14/16, but switching back to node 12 x64 worked without any issues.
