### ISSUE TITLE
Extra spaces after bullet points

### ISSUE THREAD

**Issue by omnosti** [akosbalasko/yarle#339]
When I convert an enex file, I get two extra spaces after every one of my bullet points (in total, three spaces between my bullet list marker and the content of the list item). I have exported the same notebook using both Evernote 10 and Evernote Legacy, and I've also tried using the default config as well as my own settings, but I get these extra spaces every time. [Here is an example of a converted note with the problem.](https://gist.githubusercontent.com/omnosti/488e74f86564da07bfc86ac71b5ff6d9/raw/abc433b27364507b57c961c504740be8de69cac1/Converted%2520note%2520example.md)

These extra spaces don't show up in reading mode, but I'm usually in editing mode, and it puts all my converted lists out of alignment. I'm also curious if there's a way to stop the converter from inserting a line break whenever I go from regular text to a list, because I don't have those line breaks in my original note. Thanks for reading this, and for the time you've put into Yarle.

**Comment by akosbalasko** [comment]
Hi @omnosti , I'll check it out, as it has been already raised before, we have some issues around the lists ( nested lists etc) so I can easily imagine that it's a bug.
Thank you for reporting this!

**Comment by akosbalasko** [comment]
Fix released in version 4.9.13.
