### ISSUE TITLE
The internal links processing feature produces broken links

### ISSUE THREAD

**Issue by joaosa** [akosbalasko/yarle#341]
Hey,

I was doing yet another test run and I noticed the changes in https://github.com/akosbalasko/yarle/pull/337 resulted in 2 different issues.

* ~~The post-processing step in https://github.com/akosbalasko/yarle/blob/master/src/dropTheRopeRunner.ts#L38 appears not be working in its entirety, as some of my links retain the `evernote://...` form. I will make sure to investigate this further, as it's possible I might have a few broken links myself;~~ I double-check this and one really needs to wait for the run to finish 
  * <img width="318" alt="Screen Shot 2022-01-05 at 19 42 30" src="https://user-images.githubusercontent.com/659718/148278961-f62ce236-6a06-46d1-812d-61f71f67364b.png">

* The conversion run is taking much longer. In my case, it used to take roughly one hour and now it takes almost 5 hours;
* The notebook prefix that gets added to the internal links does not match the actual notebook/enex in many of the links. I hypothesize this is related to getting the current notebook from the singleton instance.

Finally, this change doesn't seem to be necessary for the migration to work in Obsidian, as global links work just fine (provided they are unique).

Given all this, I think it would probably be wise to hide this feature under a flag, so as not to break the conversion for other users while this gets investigated :)

**Comment by akosbalasko** [comment]
Hi @joaosa ,
I fixed the first issue that you raised, I would split the others into standalone issues because one of them looks like a bug, the other would take more investigation (increased processing time), etc. and then I'd close this issue.

Thanks for your permanent help and thinking!

**Comment by joaosa** [comment]
> Hi @joaosa , I fixed the first issue that you raised, I would split the others into standalone issues because one of them looks like a bug, the other would take more investigation (increased processing time), etc. and then I'd close this issue.
> 
> Thanks for your permanent help and thinking!

you're most welcome @akosbalasko! Glad to see you looking into this :)
