### ISSUE TITLE
All notes has attachments (images) are not converted

### ISSUE THREAD

**Issue by pqnhan** [akosbalasko/yarle#342]
I use Yarle 4.7.0 to convert my evernote "enex" notebooks. The output notes are very good except that the notes containing the images are ignored during the conversion process.
I have configured it like this and tried changing the settings but it still doesn't work.

![image](https://user-images.githubusercontent.com/24197589/148712611-888058e3-96e2-48ea-8776-6b5991698dc8.png)
![image](https://user-images.githubusercontent.com/24197589/148712624-e6e3fe55-83ca-4dee-9837-abf1d450e839.png)
![image](https://user-images.githubusercontent.com/24197589/148712641-089c2a69-dff2-4b83-974c-9e7c9257b533.png)

Can you suggest me what to do?

**Comment by akosbalasko** [comment]
Hi @pqnhan ,

there is a bug in the resource sanitizer part. I release a new version today with the fix. 
Sorry for the inconviences.

**Comment by akosbalasko** [comment]
Hi @pqnhan ,
version 4.7.1 contains the fix, thank you for raising this up!
