### ISSUE TITLE
evernote Links not resolved

### ISSUE THREAD

**Issue by sk365** [akosbalasko/yarle#345]
Hi, 
thank you for this excellent app. 

However, when using it with the last MacOS binary, it turns out that no evernote:/// app links are resolved ever. 

Checking the peform URL encoding on links box in the configuration GUI menu does not help. 
Neither does creating  TOC notes in evernote.  

Please help. 

Best, 
Stefan

**Comment by akosbalasko** [comment]
Hi @sk365 !

Thank you for reporting me this issue, it's sounds really weird. 
Could you please share me the full config that you use? It's printed at the beginning of the output log. 

Thanks a lot!

**Comment by akosbalasko** [comment]
Hi @sk365 ,
Thanks for the config! I applied it on my interNotebook linking test and it looks it works as expected. 
If you don't mind, could you share with me an example where Yarle misses the link conversion? 
You can send the example to my direct mail here: akos0215@gmail.com

Thank you!
