### ISSUE TITLE
location seems not working

### ISSUE THREAD

**Issue by luochen1990** [akosbalasko/yarle#361]
Hi, I find that the location part in the template is not replaced in the result:

```
{location-block}{location}{end-location-block}
```

I'm using the latest Windows exe named `yarle-evernote-to-md-4.8.3.Setup.exe`

**Comment by luochen1990** [comment]
It works now, I'm not sure why it not works before...

**Comment by luochen1990** [comment]
I find that there is indeed some notes which keeps the `{location-block}{location}{end-location-block}` line in the result markdown file, which is unexpected, so reopen it.

**Comment by akosbalasko** [comment]
hi @luochen1990 ,

thank you for reporting this issue, i'll check it.

**Comment by akosbalasko** [comment]
hi @luochen1990 , 
Could you please send me your config settings and the template you used? 
Thank you very much!
