### ISSUE TITLE
Notes with checkboxes are not imported. 

### ISSUE THREAD

**Issue by Chriswaterguy** [akosbalasko/yarle#372]
It seems that any note with checkboxes is not imported. 

The log reports the failure:

> Failed to convert note: NOTENAME, {}

But the summary does not record that any conversions failed: 

> Conversion finished: 4 succeeded, 0 skipped, 0 failed. Total notes: 4

Thanks!

**Comment by akosbalasko** [comment]
Hi @Chriswaterguy ,
Could you please send me an example that is failed to be exported? I have some tests for checkboxes and they are converted properly, so probably something more tricky happening maybe around the different EN versions. 
You can send the enex directly to me, thank you: akos0215@gmail.com
Thanks in advance!

**Comment by Chriswaterguy** [comment]
Just noticed this is open. I eventually worked out that it was only an issue when there is a checkbox at the very beginning of the note. 

I haven't used Yarle for a long time (job complete, thank you) so I don't know if it's still an issue.
