### ISSUE TITLE
Evernote Tasks

### ISSUE THREAD

**Issue by bitic** [akosbalasko/yarle#385]
Evernote now has a Tasks feature, which I use a lot. 

I would like to export to Obsidian and use Obsidian with the "Obsidian Tasks" plugin. 

Are any plans to support converting Evernote tasks to a format that "Obsidian Tasks" can handle?

Thanks,

**Comment by akosbalasko** [comment]
Hi @bitic ! That's a great idea, I checked how tasks are exported, it looks pretty handy, so I'm glad to implement this feature soon!
thanks for raising this up!

**Comment by bitic** [comment]
This would be very useful. :-)

**Comment by akosbalasko** [comment]
Hi @bitic , I implemented the conversion of tasks (released in version 4.10.0), tried to map as many info as it can be, please take a look at it! 
Don't hesitate to contact, if you see any errors, or have some other feature requests! :)

**Comment by bitic** [comment]
That was fast. I'll check it next week.

**Comment by bitic** [comment]
I have downloaded the Yarle binary for Windows and tasks were shown like that in the markdown files:

<YARLE-EN-V10-TASK>c8531bc3-37af-421d-80b4-3401224e2285</YARLE-EN-V10-TASK>

The text of the task is gone, as the date, etc.  Is this the intended behavior?
