### ISSUE TITLE
Idea: Allow config for variable title character replace for illegal windows filename characters

### ISSUE THREAD

**Issue by jmtornetta** [akosbalasko/yarle#389]
# 06/02/2022 Update
Looks like illegal filename characters are being replaced but they are mostly being changed to '-' which erodes meaning.

I would suggest allow the user to map character replacements in the .json config. Some examples of what I might change these to:
```
: => ;
" => `
> => -gt
< => -lt
```

**Comment by akosbalasko** [comment]
Hi @jmtornetta ,
Thank you for this idea, it makes sense, but we have to take into count that we can pick only those characters which are allowed by the OS within a filename.

**Comment by jmtornetta** [comment]
Good point.

**Comment by webventurer** [comment]
Yep this is essential I think. YARLE is replacing my (>) characters with (_) and there's no way to turn it off. A character substitution map would be very helpful.
