### ISSUE TITLE
Yarle seems to be not able to convert LaTeX in EN? 

### ISSUE THREAD

**Issue by tongyx361** [akosbalasko/yarle#394]
If it can, can someone teach me how to configure? Thanks!
If it can't, will it be supported in the future?

**Comment by akosbalasko** [comment]
Hi @KiDrain61 ,

Currently it is not supported, and to be honest I thought that Evernote doesn't support Latex. But if you send me and example, I'm happy to implement it. 

here is my email address: akos0215@gmail.com

Thank you!
