### ISSUE TITLE
LogSeq Conversion not working

### ISSUE THREAD

**Issue by daveplummermd1** [akosbalasko/yarle#407]
This looks like an amazing tool.. I can convert to Obsidian, but not LogSeq
The log indicates success with this one, not enex (attached), and the directories are made (pages and assets), but the directories remain empty on completion of the conversion run.

[Y.log](https://github.com/akosbalasko/yarle/files/9568022/Y.log)
Winodws 10/Evernote 10.44.8

here is enex in ZIP:
[One in Five TIA Patients Go on to Stroke, Even in Current Era.zip](https://github.com/akosbalasko/yarle/files/9568037/One.in.Five.TIA.Patients.Go.on.to.Stroke.Even.in.Current.Era.zip)
Thanks

**Comment by akosbalasko** [comment]
Hi @daveplummermd1 ,

oh, okay, i have to investigate it, thank you for the logs and the example, i'll get back to you soon.

**Comment by akosbalasko** [comment]
Hi @daveplummermd1 ,
Thank you for raised this issue, I missed to recognise it totally. I released a new version (4.10.3) with the fix, it should work now.

**Comment by daveplummermd1** [comment]
Thank you so much for the rapid and skilled response.  May I offer the following suggestions:

1. I am unsure if I can modify the script to achieve this, but if would be nice to have "!" placed in the front position of the text that refers to a pdf.  (red arrow).

2. The tag in the original EVN appears with code around it, rather than prefixed with "#" (green arrow)

can you advise?
![YEVNL](https://user-images.githubusercontent.com/62774925/190285069-01bff1e8-cd85-44d7-9b09-bcdd0097226f.jpg)

Thanks in advance

**Comment by akosbalasko** [comment]
Hi @daveplummermd1 
I'm afraid these suggestions aren't supported currently by Yarle in case of Logseq. 
What are their behaviour in Logseq?
As they are pointing to different requests, please create separated feature request stories for each of them, I would close this bug report.
