### ISSUE TITLE
how to attach pictures to the same notebook folder？

### ISSUE THREAD

**Issue by sjbz** [akosbalasko/yarle#414]
i use yarle to transform Evernote to obsidian
but every single notebook output like this kind：
/notebook1
/notebook1/notebook1.md
/notebook1/assets
/notebook1/assets/0.jpg
/notebook1/assets/1.jpg
/notebook1/assets/3.jpg
/notebook1/assets/4.jpg
…
how can i set to make output like this？

**Comment by akosbalasko** [comment]
Hi @sjbz , sorry for this long delay, I missed your issue. 
Setting ```haveGlobalResources``` to true should do the job.
