### ISSUE TITLE
when I run cmd and type the command you post, there is some error.

### ISSUE THREAD

**Issue by secondbrain-note** [akosbalasko/yarle#42]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'xml-stream'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Sophia\dist\yarle.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yarle-evernote-to-md@2.8.0 start: `node --max-old-space-size=1024 ./dist/dropTheRope.js "--enexSource=GeneralNotes.enex" "--outputDir=./out" "--include-metadata" "--zettelkasten" "--plaintext-notes-only" "--outputFormat=ObsidianMD"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yarle-evernote-to-md@2.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sophia\AppData\Roaming\npm-cache\_logs\2020-08-15T12_18_58_698Z-debug.log

**Comment by secondbrain-note** [comment]
where should I put the **yarle.zip** in my computer? Do I need to unzip it? 
I never used python or node.js before.

**Comment by akosbalasko** [comment]
Hi! Did you run 'npm i' and 'npm run build' before executing the code?
Answering your second question, you can put it whenever you want, as when you execute the code you must specify the location of the exported Evernote file in the argument of 'execSource'. The example call can be called in the root folder of Yarle.

**Comment by secondbrain-note** [comment]
I used another computer(win10,64bit), install node.js10.18.1, run"npm i" and"npm run build",still these error

C:\Users\(my user name)>npm i
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\(my user name)\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\(my user name)\package.json'
npm WARN (my user name) No description
npm WARN (my user name) No repository field.
npm WARN (my user name) No README data
npm WARN (my user name) No license field.

up to date in 1.271s
found 0 vulnerabilities


C:\Users\(my user name)>npm run build
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\(my user name)\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\(my user name)\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\(my user name)\AppData\Roaming\npm-cache\_logs\2020-08-15T23_41_34_274Z-debug.log

**Comment by akosbalasko** [comment]
These commands (npm i, npm run build) must be invoked in the root folder of yarle.
