### ISSUE TITLE
Option to turn off automatic heading creation

### ISSUE THREAD

**Issue by Karut** [akosbalasko/yarle#422]
As I understand it for every note the title is put as heading at the top of each note so that the title of the note is converted without the possibility of it missing. My notes titles seem to be imported into Obsidian just fine (from the file name I guess?). Can I turn of the automatic creation of heading then with a config option? Seems pretty cumbersome to remove the headings of thousands of my converted notes or am I missing something? 

Thanks!

**Comment by akosbalasko** [comment]
Hi @Karut ,
No, Yarle generates the notes according to the template specified in the UI or by using a default template. 
I think it is an Obsidian-specific feature, it automatically shows the filename in the header of the open file, here is a screenshot: 

<img width="1140" alt="Screenshot 2022-11-23 at 20 02 48" src="https://user-images.githubusercontent.com/11886731/203627838-6c6917b8-1905-47e2-8ad3-a24b99522c63.png">

To deactivate it you can set "Show inline title” toggle to disabled in "settings → appearance".

**Comment by Karut** [comment]
> Hi @Karut , No, Yarle generates the notes according to the template specified in the UI or by using a default template. I think it is an Obsidian-specific feature, it automatically shows the filename in the header of the open file, here is a screenshot:
> 
> <img alt="Screenshot 2022-11-23 at 20 02 48" width="1140" src="https://user-images.githubusercontent.com/11886731/203627838-6c6917b8-1905-47e2-8ad3-a24b99522c63.png">
> 
> To deactivate it you can set "Show inline title” toggle to disabled in "settings → appearance".

Thanks for the info, I learned something!
