### ISSUE TITLE
Change file name based on note content

### ISSUE THREAD

**Issue by trijste** [akosbalasko/yarle#424]
I can't see a way to do this, but it may already be possible. I want to be able to change the names of the files generated to the date they were created instead of their title. I can't see a way to do this in the options or template.

**Comment by trijste** [comment]
Hey, that's pretty sweet! It may be particular to my use case. Take your time. I'm happy to wait for your more pressing activities to resolve.

**Comment by akosbalasko** [comment]
Hi @trijste ,
I added a new option (useZettelIdAsFilename), just click on its checkbox in the UI, and the zettel IDs (creation dates) will be used as filenames. 
Feel free to open another issue, if something is still missing!
