### ISSUE TITLE
On Start Conversion App Freezing

### ISSUE THREAD

**Issue by davidganz** [akosbalasko/yarle#436]
Hi!

I'm trying to run your App on Ubuntu 22.04.
When I try to choose "Start Conversion" apparently nothing is happening and after in the second tentative the App was Crashing...
After I found several Notes in the target conversion location. The problem is also that I have a huge notebook of about 60mb, and without a sign that the conversion is running is difficult to know how much to wait or what to do. Should be enough some visible sign that the Conversion is in Progression...

Moreover I intend to signal you how the "Set up your template" in Step 3 is not understardable at all.
The same also for the npx command on Shell... You should first specify what's meaning, and again if it's needed or not.
Let me know.

                Best regards,
                                David

**Comment by akosbalasko** [comment]
Hi @davidganz ,

Please check the description about templates here: https://github.com/akosbalasko/yarle/blob/master/Templates.md , it should be mentioned in the intro of yarle, and it is linked in Readme here. 
npx command is the command-line variant of Yarle, if you would like to use it with UI, then npx is unnecessary for you. 

About the crashing: are there any logs, or could you please provide me some screenshots of your settings and crash error message? 
Thanks! 
akos
