### ISSUE TITLE
Exporting using LogSeq journal format loses content

### ISSUE THREAD

**Issue by noofny** [akosbalasko/yarle#444]
When you export using LogSeqMD and enable journal format, if you have multiple source notes for the same create date then only one is kept (seems to be the one with the earliest timestamp), which obviously results is a lot of data not being converted. Instead of this, you could look for an existing output file (eg `2023-01-30.md`) and if the file exists, just append to it.

This would be very helpful for people wanting to migrate from a "standalone note" format to a "journal" format. Sorry if I missed something but I couldn't see a configuration option for this, please let me know if I just missed it?

Thank you!

**Comment by akosbalasko** [comment]
Hi @noofny ,

Good point, I think i see the problem, let me try to resolve it soon, it doesn't look so complicated.

**Comment by noofny** [comment]
That workaround you suggested would be a massive improvement until you get a longer term fix in, for sure! Thank you again for the quick response @akosbalasko !

**Comment by akosbalasko** [comment]
@noofny I checked it in the code, and the creation time e.g. the file name of the Journal note can be configured by the dateFormat property, so if you set it to be unique, like set the time granularity down to milliseconds, then it will (almost) guarantee that the notes will be unique. 
dateFormat must be the ISO 8601 specification of the expected date format, so something like this:
dateFormat: YYYY-MM-DDThhmmss.sss

**Comment by noofny** [comment]
Okay I gave that a shot and it works as you explained, so yeah this would be good enough as a workaround for now. Obviously it would require a lot of manual editing by hand to achieve the end result, so ideally the idea I proposed of appending to an existing journal file with the correct filename format of `YYYY-MM-DD.md` would be amazing if it's possible. 

Thanks again for helping pointing out this useful workaround!

**Comment by akosbalasko** [comment]
@noofny , Okay then, so instead of having the postfix-based workaround, I'd fix the core problem by appending the journal notes. Hopefully it will be fixed soon, I keep you posted.

**Comment by noofny** [comment]
Thank you @akosbalasko - I bought you a couple of coffees to help :-)

**Comment by akosbalasko** [comment]
@noofny , wow, great, thanks a lot! :) 

I run into an open question, probably you can answer it better and faster instead of letting me decide something that would turn out that doesn't fit you. 
So, currently, I solved the appendance to the journal notes, but the problem is that I append the whole generated note after the previous one with titles and metadata content. This is the current outcome: 

```
# test - note with picture

- Squirrels 
- ![0_pic.jpg](./_resources/2018-10-06T09:43:49+01:00.resources/0_pic.jpg)

    Created at: 2018-10-06T09:43:49+01:00
    Updated at: 2018-10-06T10:12:11+01:00

# test -note with text only

- This is the content

    Created at: 2018-10-06T09:43:49+01:00
    Updated at: 2018-10-06T09:44:11+01:00


```
So, it hurts my eyes that the metadata and the title have been added twice (I mean, they are not 'unified, or merged or something', which in one way it makes sense, because they are data, and we should not lose content anymore, including the update date which may be different in case of the two notes. 

So, how it should be resolved? 
**Plan A: keep it as it is, release this current 'solution'**
- Pros:
  -  we do not lose information
  - fast implementation as it is done mainly
- Cons:
  - Ugly

**Plan B: unify titles and metada**
 - Pros:
   - way more clear notes will be generated
 - Cons:
   -  we lose the info
   - requires more development, requires more time
  
 **Plan C: mixture of A and B, create simple title like: 'Journal for day.. and put the titles as main bullet points**
 In this case how we manage the metadata coming from the different notes e.g. different update times? 
 - Pros:
   - no data loss
   - Clear note structure
 - Cons:
   - this plan requires the most dev. time
  
   
 ++ In case of planB or planC, I can release the current 'ugly' version for you if you want (like in plan A), in this case you don't have to wait for the fine-tuned version, but it's disadvantage is that it requires a bit of manual work to 'clear'  or uniform the journal notes. 
 
 Which plan do you prefer?

**Comment by noofny** [comment]
I love your passion, interest and ideas! 

Have taken a quick look at your suggested approaches and I think I have some ideas but can you let me try some things out and get back to you tomorrow please? As you know, we must honor markdown standards and prevent things from getting messy/ugly, so leaving this to be configured via a user template may be a bad idea, I agree. I'll come back to you soon (within 24 hours) if that's cool?

Thanks again for letting me help improve your work.

**Comment by akosbalasko** [comment]
@noofny sure thing, take your time! Thanks for your thinking on it!

**Comment by noofny** [comment]
Hi @akosbalasko - so I gave this some thought overnight and personally I believe the most useful and appropriate approach is a mix of *Plan A* and *Plan C*.

- Each journal file starts with a "static" h1 main title, something like `# Journal Notes for YYYY-MM-DD`
- Each note is then appended using the existing template mechanism for formatting. This way it keeps all content, leaves the decision up to the user how they want it to look and (hopefully) is less effort for you to change in code too.

### Examples

I'll give examples below for a journal file `2023-01-30.md` created from 2 notes created on that same day.

#### Example 1 - "h2" Note Titles

User specifies a title block `{title-block}## {title}{end-title-block}` which results in each note title having a single h2 title (which honors proper markdown schema and looks nice).

```text
# Journal Notes for 2023-01-30

## Note 1 Title - Squirrels

- Squirrels are awesome
- ![0_pic.jpg](./_resources/2018-10-06T09:43:49+01:00.resources/0_pic.jpg)

    Created at: 2023-01-30T09:43:49+01:00
    Updated at: 2023-01-31T10:12:11+01:00

## Note 2 Title - Hello World

- This is some content about hello world

    Created at: 2023-01-30T09:43:49+01:00
    Updated at: 2023-01-30T09:44:11+01:00
```

#### Example 2 - Duplicate "h1" Note Titles

User specifies a title block `{title-block}# {title}{end-title-block}` which results in each note title having a duplicate h1 title (which dishonors proper markdown schema and looks ugly).

```text
# Journal Notes for 2023-01-30

# Note 1 Title - Squirrels

- Squirrels are awesome
- ![0_pic.jpg](./_resources/2018-10-06T09:43:49+01:00.resources/0_pic.jpg)

    Created at: 2023-01-30T09:43:49+01:00
    Updated at: 2023-01-31T10:12:11+01:00

# Note 2 Title - Hello World

- This is some content about hello world

    Created at: 2023-01-30T09:43:49+01:00
    Updated at: 2023-01-30T09:44:11+01:00
```

What do you think?

**Comment by akosbalasko** [comment]
hi @noofny ,
Good thinking, I only see some challenges around its implementation, but this is my problem :) 

For example we have to provide general solution for Logseq, meaning that if the user changes the template, the change will take effect on the 'simple' notes as well, so, if they change the title to start with h2 headers, the simple notes will follow this solution as well. Do you think that it could be a problem? Or could we change the template to ## as titles by default, to allow h1 for the merged journal notes' static title? So a simple journal note would look like this (h2 header as a title): 

```
## Note 1 Title - Squirrels

- Squirrels are awesome
- ![0_pic.jpg](./_resources/2018-10-06T09:43:49+01:00.resources/0_pic.jpg)

    Created at: 2023-01-30T09:43:49+01:00
    Updated at: 2023-01-31T10:12:11+01:00

```
and the merged journal note would look like what you showed on Example 1.

How about this?

**Comment by noofny** [comment]
Hey @akosbalasko - yeah that sounds cool. I can't see it being a problem at this stage.

Let me know once you get a change if you need a hand testing, happy to help out there.

**Comment by akosbalasko** [comment]
Hi @noofny ,
Thanks for the offer, I created a test to make sure that nothing break and the modification produces the result what we agreed on. I released a new version (5.0.4), could you please confirm that now it works as expected? 
Thanks a lot!

**Comment by noofny** [comment]
Amazing! Sure thing @akosbalasko - will try it out and let you know.

**Comment by noofny** [comment]
Hey @akosbalasko - Thank you! I have tested it out with a small notebook export, just getting some larger (more real-world) exports happening and will test those as a final step. So far it looks rock solid, just as we expected, I will report back within the next couple of days and I reckon we are good to close this ticket unless anything strange appears. Will let you know.

**Comment by noofny** [comment]
@akosbalasko - mate it's looking perfect! Have tested it out with a larger export and played around with some variable settings and it's amazing. Thank you for not only creating this tool but for so passionately maintaining it, you've helped yet another person to decouple their life from the clutches of Evernote! Awesome work mate 🌻 🙇‍♂️

**Comment by akosbalasko** [comment]
Thank you @noofny ! :)
