### ISSUE TITLE
How to use config.json with yarle?

### ISSUE THREAD

**Issue by paterczm** [akosbalasko/yarle#448]
Hello!

I installed yarle from rpm on my Fedora system. yarle-evernote-to-md command starts the UI where I can set things in forms, but I see no way to tell it to use a config.json. Can you help me?

I also tried this method:
```
npx -p yarle-evernote-to-md@latest yarle --include-metadata --configFile ./config.json
```

But the command gets stuck with cpu usage at 100%. Nothing is migrated.

Thank you

Marek

**Comment by akosbalasko** [comment]
Hi @paterczm ,

if you use Yarle with the UI, you don't have to deal with the config.json, it will be generated automatically when you set your configuration options (in step 3 there are many options about tags, output format etc... those settings will be used as a config )
