### ISSUE TITLE
Internal Evernote links remain unconverted

### ISSUE THREAD

**Issue by chookster** [akosbalasko/yarle#450]
Hi Akos... I have been testing Yarle 5.0.4 on various Evernote .enex files and it seems that many, or all, internal Evernote links are not being converted.  It is possible that I am not choosing the correct options on the Configuration page, but for some tests, the configuration has been left untouched using 100% of the default settings.
A copy of the complete log file and a list of unconverted links is attached. Please note, this issue was also mentioned  [in the Obsidian forum](https://forum.obsidian.md/t/from-evernote-to-obsidian/9956/33?u=chookster)

[2023-02-20 - Unconverted EN links.zip](https://github.com/akosbalasko/yarle/files/10788513/2023-02-20.-.Unconverted.EN.links.zip)

**Comment by akosbalasko** [comment]
HI @chookster ,
I merged a fix which should solve the issue, it is released as version 5.0.6
Could you please try to convert the notes again with the latest Yarle version?
Thanks a lot!

**Comment by chookster** [comment]
Hi Akos... Thank you for fixing the issue so quickly. I have just tested 5.0.6 on the same set of notebooks and all internal links have converted OK.

**Comment by akosbalasko** [comment]
Hi @chookster, perfect, thanks for the confirmation!

**Comment by chookster** [comment]
Hi Akos... I did some further testing and 5.0.6 is converting internal links OK. But I made a user error when checking links that others may also make in the future. You may wish to point this out in the README notes. The error is written up in the [From Evernote to Obsidian](https://forum.obsidian.md/t/from-evernote-to-obsidian/9956/37?) topic in the Obsidian forum.
