### ISSUE TITLE
Evernote folder names including a period are truncated

### ISSUE THREAD

**Issue by chookster** [akosbalasko/yarle#455]
Hi Akos.... If some folders in Evernote contain a period in their name, Yarle 5.0.7 seems to recognise only the characters to the left of the period. So a folder in Evernote called 'a.folder-name' will export to Obsidian as 'a'. It could be the Evernote exporter causing this problem but I haven't checked that.

**Comment by akosbalasko** [comment]
Hi @chookster !
What do you mean on 'folder' in Evernote? The notebook?

**Comment by chookster** [comment]
Yes. Sorry to use confusing terminology. Here is an example of what happens.
We have five notebooks in Evernote, each containing five notes.

- a.cat   (5)
- a.dog   (5)
- a.mouse  (5)
- a.snake   (5)
- a.elephant   (5)

Each notebook is exported as an .enex file.

- a.cat.enex
- a.dog.enex
- a.mouse.enex
- a.snake.enex
- a.elephant.enex

Then when these files are exported using Yarle into Obsidian, we get a single folder containing all 25 messages.
- a   (25).

**Comment by akosbalasko** [comment]
@chookster 
Oh, okay, thanks for the sympthoms, I'm on it.

**Comment by akosbalasko** [comment]
Hi @chookster 
It is fixed in 5.0.8, please check it out.
I'd close this issue, but don't hesitate to comment here, if the problem still appears on your side. (I made a unit test for this case, so I'd be really surprised, but anyway :) )

**Comment by chookster** [comment]
Hi Akos... unfortunately the issue remains. It occurred in two different batches of .enex files exactly the same result as 5.0.7.

**Comment by chookster** [comment]
Hi Akos... yes 5.0.8 is processing the prefixed enex files (eg a.cat.enex) correctly now. Thank you.
