### ISSUE TITLE
some local image links not working: ![](../attachments/unknown_filename-0e59eda7.png =678x)

### ISSUE THREAD

**Issue by jdninqld** [akosbalasko/yarle#457]
![image](https://user-images.githubusercontent.com/127082851/223045222-815d029a-db10-4ce3-b8b1-777d4fea3184.png)

Have been trying to get a trivial test set of notes to convert cleanly.

The conversion mostly works (thx!), but some local image links are not converting cleanly.

e.g. ![](../attachments/unknown_filename-0e59eda7.png =678x)

I'm going to guess that the image links that convert cleanly are those that I didn't resize in evernote and the ones that break are the ones that were manually resized in evernote.

converted using: 
yarle v5-0-8
current evernote v10. I also tried initially in legacy before then trying current v10 and the behaviour is the same in both versions.

Changing "Keep Image Size" from Yes to No makes no difference. I checked the logs - below - and I don't immediately see any difference in the "Keep Image size" setting as reported in the two logs.

>>> Log: executed with "keep image size": Yes: <<<

Current config is: {
    "enexSources": [
        "G:\\evernote bu\\evernote v10 exports\\01-02a earnings - ep.enex"
    ],
    "outputDir": "G:\\evernote bu\\evernote v10 exports",
    "keepOriginalHtml": false,
    "isMetadataNeeded": true,
    "isNotebookNameNeeded": false,
    "isZettelkastenNeeded": false,
    "useZettelIdAsFilename": false,
    "plainTextNotesOnly": false,
    "skipWebClips": true,
    "useHashTags": true,
    "nestedTags": {
        "separatorInEN": "_",
        "replaceSeparatorWith": "---",
        "replaceSpaceWith": "-"
    },
    "outputFormat": "ObsidianMD",
    "taskOutputFormat": "ObsidianMD",
    "obsidianTaskTag": "",
    "urlEncodeFileNamesAndLinks": false,
    "sanitizeResourceNameSpaces": false,
    "replacementChar": "_",
    "pathSeparator": "/",
    "resourcesDir": "attachments",
    "turndownOptions": {
        "headingStyle": "atx"
    },
    "skipLocation": true,
    "skipCreationTime": false,
    "skipUpdateTime": false,
    "skipSourceUrl": false,
    "skipTags": false,
    "skipEnexFileNameFromOutputPath": false,
    "keepMDCharactersOfENNotes": false,
    "monospaceIsCodeBlock": false,
    "currentTemplate": "---\r\n\r\n{created-at-block}_Created at {created-at}._{end-created-at-block}\r\n{updated-at-block}_Last updated at {updated-at}._{end-updated-at-block}\r\n{source-url-block}_Source URL: []({source-url})._{end-source-url-block}\r\n\r\n\r\n{tags-block}\r\nTagged: \r\n```\r\n{tags}\r\n```\r\n{end-tags-block}\r\n\r\n---\r\n\r\n{title-block}# {title}{end-title-block}\r\n\r\n\r\n{content-block}{content}{end-content-block}\r\n\r\n",
    "logseqSettings": {
        "journalNotes": false
    },
    "obsidianSettings": {
        "omitLinkDisplayName": false
    },
    "dateFormat": "YYYY-MM-DD",
    "keepImageSize": "StandardMD",
    "keepOriginalAmountOfNewlines": true,
    "addExtensionToInternalLinks": true,
    "haveEnexLevelResources": false,
    "haveGlobalResources": true,
    "useUniqueUnknownFileNames": true
}
Path separator:\
path G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep created
Getting stream from G:\evernote bu\evernote v10 exports\01-02a earnings - ep.enex

Conversion started at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Converting note "2023-03-02 ai"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename-776cf98c.png added
mediaReference src ../attachments/unknown_filename-aac7bdc5.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2023-03-02 ai.md
Conversion finished at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Note "2023-03-02 ai" converted successfully in 0.055 seconds.
Notes processed: 1

Conversion started at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Converting note "2023-02-16 twlo"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename-0e59eda7.png added
mediaReference src ../attachments/Image.png added
mediaReference src ../attachments/unknown_filename-0162b61a.png added
mediaReference src ../attachments/unknown_filename-50f97ca7.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2023-02-16 twlo.md
Conversion finished at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Note "2023-02-16 twlo" converted successfully in 0.401 seconds.
Notes processed: 2

Conversion started at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Converting note "2023-02-07 slqt"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename-7680824e.png added
mediaReference src ../attachments/unknown_filename-d9a059ff.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2023-02-07 slqt.md
Conversion finished at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Note "2023-02-07 slqt" converted successfully in 0.022 seconds.
Notes processed: 3

Conversion started at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Converting note "2022-12-08 rent"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename-c0e396df.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2022-12-08 rent.md
Conversion finished at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Note "2022-12-08 rent" converted successfully in 0.016 seconds.
Notes processed: 4

Conversion started at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Converting note "2022-11-15 tblt"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename-ee1073ee.png added
mediaReference src ../attachments/unknown_filename-098aca4e.png added
mediaReference src ../attachments/unknown_filename-affc8090.png added
mediaReference src ../attachments/unknown_filename-f0a008ad.png added
mediaReference src ../attachments/unknown_filename-2f1816e0.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2022-11-15 tblt.md
Conversion finished at Mon Mar 06 2023 17:00:31 GMT+1000 (Australian Eastern Standard Time)
Note "2022-11-15 tblt" converted successfully in 0.03 seconds.
Notes processed: 5

==========================
Conversion finished: 5 succeeded, 0 skipped, 0 failed. Total notes: 5

>>> Log: executed with "keep image size": No <<<

Current config is: {
    "enexSources": [
        "G:\\evernote bu\\evernote v10 exports\\01-02a earnings - ep.enex"
    ],
    "outputDir": "G:\\evernote bu\\evernote v10 exports",
    "keepOriginalHtml": false,
    "isMetadataNeeded": true,
    "isNotebookNameNeeded": false,
    "isZettelkastenNeeded": false,
    "useZettelIdAsFilename": false,
    "plainTextNotesOnly": false,
    "skipWebClips": true,
    "useHashTags": true,
    "nestedTags": {
        "separatorInEN": "_",
        "replaceSeparatorWith": "---",
        "replaceSpaceWith": "-"
    },
    "outputFormat": "ObsidianMD",
    "taskOutputFormat": "ObsidianMD",
    "obsidianTaskTag": "",
    "urlEncodeFileNamesAndLinks": false,
    "sanitizeResourceNameSpaces": false,
    "replacementChar": "_",
    "pathSeparator": "/",
    "resourcesDir": "attachments",
    "turndownOptions": {
        "headingStyle": "atx"
    },
    "skipLocation": true,
    "skipCreationTime": false,
    "skipUpdateTime": false,
    "skipSourceUrl": false,
    "skipTags": false,
    "skipEnexFileNameFromOutputPath": false,
    "keepMDCharactersOfENNotes": false,
    "monospaceIsCodeBlock": false,
    "currentTemplate": "---\r\n\r\n{created-at-block}_Created at {created-at}._{end-created-at-block}\r\n{updated-at-block}_Last updated at {updated-at}._{end-updated-at-block}\r\n{source-url-block}_Source URL: []({source-url})._{end-source-url-block}\r\n\r\n\r\n{tags-block}\r\nTagged: \r\n```\r\n{tags}\r\n```\r\n{end-tags-block}\r\n\r\n---\r\n\r\n{title-block}# {title}{end-title-block}\r\n\r\n\r\n{content-block}{content}{end-content-block}\r\n\r\n",
    "logseqSettings": {
        "journalNotes": false
    },
    "obsidianSettings": {
        "omitLinkDisplayName": false
    },
    "dateFormat": "YYYY-MM-DD",
    "keepImageSize": "StandardMD",
    "keepOriginalAmountOfNewlines": false,
    "addExtensionToInternalLinks": true,
    "haveEnexLevelResources": false,
    "haveGlobalResources": true,
    "useUniqueUnknownFileNames": false
}
Path separator:\
path G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep created
Getting stream from G:\evernote bu\evernote v10 exports\01-02a earnings - ep.enex

Conversion started at Mon Mar 06 2023 17:06:28 GMT+1000 (Australian Eastern Standard Time)
Converting note "2023-03-02 ai"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename.png added
mediaReference src ../attachments/unknown_filename.1.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2023-03-02 ai.md
Conversion finished at Mon Mar 06 2023 17:06:28 GMT+1000 (Australian Eastern Standard Time)
Note "2023-03-02 ai" converted successfully in 0.052 seconds.
Notes processed: 1

Conversion started at Mon Mar 06 2023 17:06:28 GMT+1000 (Australian Eastern Standard Time)
Converting note "2023-02-16 twlo"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename.2.png added
mediaReference src ../attachments/Image.png added
mediaReference src ../attachments/unknown_filename.3.png added
mediaReference src ../attachments/unknown_filename.4.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2023-02-16 twlo.md
Conversion finished at Mon Mar 06 2023 17:06:28 GMT+1000 (Australian Eastern Standard Time)
Note "2023-02-16 twlo" converted successfully in 0.405 seconds.
Notes processed: 2

Conversion started at Mon Mar 06 2023 17:06:28 GMT+1000 (Australian Eastern Standard Time)
Converting note "2023-02-07 slqt"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename.5.png added
mediaReference src ../attachments/unknown_filename.6.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2023-02-07 slqt.md
Conversion finished at Mon Mar 06 2023 17:06:28 GMT+1000 (Australian Eastern Standard Time)
Note "2023-02-07 slqt" converted successfully in 0.022 seconds.
Notes processed: 3

Conversion started at Mon Mar 06 2023 17:06:28 GMT+1000 (Australian Eastern Standard Time)
Converting note "2022-12-08 rent"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename.7.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2022-12-08 rent.md
Conversion finished at Mon Mar 06 2023 17:06:28 GMT+1000 (Australian Eastern Standard Time)
Note "2022-12-08 rent" converted successfully in 0.015 seconds.
Notes processed: 4

Conversion started at Mon Mar 06 2023 17:06:29 GMT+1000 (Australian Eastern Standard Time)
Converting note "2022-11-15 tblt"...
relative resource work dir: ../attachments
absolute resource work dir: G:\evernote bu\evernote v10 exports\notes\attachments
mediaReference src ../attachments/unknown_filename.8.png added
mediaReference src ../attachments/unknown_filename.9.png added
mediaReference src ../attachments/unknown_filename.10.png added
mediaReference src ../attachments/unknown_filename.11.png added
mediaReference src ../attachments/unknown_filename.12.png added
Note saved to G:\evernote bu\evernote v10 exports\notes\01-02a earnings - ep\2022-11-15 tblt.md
Conversion finished at Mon Mar 06 2023 17:06:29 GMT+1000 (Australian Eastern Standard Time)
Note "2022-11-15 tblt" converted successfully in 0.048 seconds.
Notes processed: 5

==========================
Conversion finished: 5 succeeded, 0 skipped, 0 failed. Total notes: 5

**Comment by akosbalasko** [comment]
Hi @jdninqld !
Thank you for raising this issue! I have a feeling that the changes of the UI and the node.js version upgrade may affected the default behaviour (like keepImageSize does not take effect and others), therefore I'd like to ask you to try the old version of Yarle, here it is: https://github.com/akosbalasko/yarle/releases/tag/v4.16.0
Until I try to fix the UI case to handle the keepSize correctly. 
The other option is that Evernote changed something on their own format that caused these problems. Could you please tell me which version of Evernote do you use for export your notes? 

Thanks a lot!

**Comment by akosbalasko** [comment]
@jdninqld 
Yes, I think it was mainly due to the UI, sorry about that. I released a new version (5.0.9), please set Keep Image size to Yes to make it work for Obsidian.
I'd close this issue, but don't hesitate to comment here, or open a new one if you still face some problems! 

Thanks again!

**Comment by jdninqld** [comment]
thx. works. appreciated.
