### ISSUE TITLE
On Mac GUI Version, Add 'md' extension of internal links not respected

### ISSUE THREAD

**Issue by dgreen** [akosbalasko/yarle#488]
Choosing "No" does not keep "/.md" (also an issue -- no "/")  from being appended.

Looking in the  ApplicationSupport/yarle-evernote-to-md/config.json
the option is

	"addExtensionToInternalLinks": true,

even though "no" was chosen.

**Comment by dgreen** [comment]
Sometimes it is "/.md" and sometimes it is just ".md".  Either way, the GUI request to not include extensions is failing.  I have not been able to deduce why some are "/.md" and some are ".md".

**Comment by akosbalasko** [comment]
Hi @dgreen ,

Okok, I'll investigate it soon. 
Cheers,
akos

**Comment by akosbalasko** [comment]
Hi @dgreen ,
the toggle should work now in version 5.2.1
cheers,
akos
