### ISSUE TITLE
non http: URLs not handled correct

### ISSUE THREAD

**Issue by dgreen** [akosbalasko/yarle#489]
URLs that are text with links like "tel:xxx-xxx-yyyy" and "busycal:.*" are translated into

[[tel:xxx-xxx-yyyy|text]]

but should be 

[text](tel:xxx-xxx-yyyy)

**Comment by akosbalasko** [comment]
Hi @dgreen , 

Thanks for reporting this. So it means that in Evernote you have a link with some text, but the link itself should not be a link itself, but just a simple text? But in this case we loose the real tel number in the converted md file. I think the link recognition in your target note-taking app (Obsidian, Tana, Logseq or others) could be improved to recognize "tel:" prefixes differently. 
So, I'm not sure that Yarle conversion misses the thing, I think it works correctly.

**Comment by dgreen** [comment]
Hi @akosbalasko ,

Thanks for the reply.

I disagree (and probably have explained it poorly before).

My understanding is

In Evernote, all links protocol:info.  Most links are created using ⌘+K (Mac) and then show up as underlined text with the protocol:info behind the scenes.

For links referring to pages in Evernote, the link is evernote:info, and the underlined text is likely to be the title of another Evernote page.  Yarle (for Obsidian mode) transforms these to WikiLinks where

[[present name|text]] is the Markdown-like encoding in the file

For links referring to web pages, the link is http://url-info and Yarle transforms these to markdown links

[text](http://url-info)

For links referring to other things like telephone numbers, the link is tel:number and Yarle is encoding them as WikiLinks

[[tel:number|text]]

where I think they should be, for all protocols besides evernote (and accommodations for embedded images not discussed here), as markdown links

[text](tel:number)

This later encoding works in many places, including Obsidian, vscode, Typora, browsers, etc., to generate HTML that works when you click on it.

**Comment by dgreen** [comment]
Put code escapes into 2 places where GitHub hid the point being made in the above comment.

**Comment by akosbalasko** [comment]
Hi @dgreen ,

Okay, thanks for the clarification, now I get it. I fix it soon.

**Comment by akosbalasko** [comment]
Fixed and released in v5.5.8.

**Comment by dgreen** [comment]
Fixed for tel: -- Thanks.

But other uri's that are of the form protocol://stuff are still translated into [[protocol://stuff]].

For example, I had calendar events that the text was something like 2022-09-22 and the link was busycalevent://info/B8281E75-90CB-4AF3-9D94-7D65D32E5E08+685556400 .  The Yarle generated output is only [[busycalevent://info/B8281E75-90CB-4AF3-9D94-7D65D32E5E08+685556400|2022-09-22]] .  I guess this is technically correct (it does look correct visually) but it would be helpful if it were coded (either by default or option) as [2023-04-09](busycalevent://info/D96E87D2-5BA5-48E9-BD46-4A980818E00A+702406800|2023-04-09)

Obsidian seems to need this although it looks like Drafts handles the Wikilink plus alias as presently encoded.  Thanks for considering.

**Comment by akosbalasko** [comment]
HI @dgreen ,

Oh, okay, I was focusing on standard http protocols. 
I'll add support of BusyCall sool, hopefully today. 

Cheers,
akos

**Comment by dgreen** [comment]
Thanks.

You might want to consider the generic pattern of URI’s  when presented a
link from evernote for [name](uri) treatment.

https://en.m.wikipedia.org/wiki/Uniform_Resource_Identifier

See second paragraph of Syntax section.

**Comment by akosbalasko** [comment]
HI @dgreen ,
Thank you! 
I released version 5.7.0 that handles busycals correctly.

**Comment by dgreen** [comment]
Thanks.

Just for completeness, stating the obvious regarding the generic URI, “except for “evernote://“.

Best regards.

**Comment by akosbalasko** [comment]
Sure sure I could do it, but I don't want to have this more general solution because I don't wanna allow other "non-standard" protocols, or data:// etc, just state which options are allowed. 
Cheers,
akos
