### ISSUE TITLE
Underline is not preserved

### ISSUE THREAD

**Issue by kazukiotsuka** [akosbalasko/yarle#492]
I appreciate this great work. I'm seriously considering migration from EN to Obsidian but just one thing to give up.
The underline is not preserved:

**Before conversion**
![Screenshot 2023-07-21 at 11 25 04](https://github.com/akosbalasko/yarle/assets/3203107/7f81835a-246f-4dc6-a351-b35b2258797d)

**After conversion**
![Screenshot 2023-07-21 at 11 25 31](https://github.com/akosbalasko/yarle/assets/3203107/51d3b2b1-54a0-4370-abcc-f3872e4f7d78)

If the location in texts having underline is specified in .enex, I believe that it would be possible by replacing them into  
`<u></u>`

Are there others who wait this function? Or this issue is more difficult than I thought?

**Comment by akosbalasko** [comment]
Hi @kazukiotsuka ,
I have to double-check it, it should work.

**Comment by kazukiotsuka** [comment]
@akosbalasko I tried a plugin named Underline. The bold and underline don't seem to work simultaneously in the Markdown.

**Comment by akosbalasko** [comment]
Implemented in v5.6.0

**Comment by nikhilmaddirala** [comment]
> Implemented in v5.6.0

Could you clarify how exactly this was implemented considering that markdown doesn't support underlining? Thank you!
