### ISSUE TITLE
Question mark in title in Evernote ends up as underscore

### ISSUE THREAD

**Issue by boardtc** [akosbalasko/yarle#503]
I'm not sure if this is a enex conversion issue or a Yarle one but my evernote ended in a question mark and after the conversion the file and title end with an underscore. Is anyone aware?

Looking at the log it says:

Converting note "Does WD 40 remove limescale?"...
Note saved to G:\My Drive\Backup\Evernote\Test output\notes\DIY\Does WD 40 remove limescale_.md

**Comment by akosbalasko** [comment]
Hi @boardtc ,

From version 5.5.0 some characters can be configured to be replaced by some others, including question mark, pls check the config description on the main page. If you would like to keep that character, just remove
```
,
"?": "_",
```
from config.
