### ISSUE TITLE
Yarle via command line is broken

### ISSUE THREAD

**Issue by lroche** [akosbalasko/yarle#533]
Because https://github.com/maugenst/zip-a-folder/issues/49
Actually, the dependency used by Yarle `zip-a-folder` branch 2.x (>2.0.1) doesn't support commonjs loading anymore.

So There is a fatal error during the process while using yarle via command line:

/Users/lionel/Library/pnpm/store/v3/tmp/dlx-5142/node_modules/.pnpm/yarle-evernote-to-md@5.8.0_electron@26.2.2/node_modules/yarle-evernote-to-md/dist/utils/heptabase/zip-folder.js:4

const zip_a_folder_1 = require("zip-a-folder");

                       ^

  

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/lionel/Library/pnpm/store/v3/tmp/dlx-5142/node_modules/.pnpm/zip-a-folder@2.0.2/node_modules/zip-a-folder/dist/lib/ZipAFolder.js from /Users/lionel/Library/pnpm/store/v3/tmp/dlx-5142/node_modules/.pnpm/yarle-evernote-to-md@5.8.0_electron@26.2.2/node_modules/yarle-evernote-to-md/dist/utils/heptabase/zip-folder.js not supported.
[...]
 ERROR  Command failed with exit code 1: yarle yarle --configFile ./myConfig.json

**Upgrade dependency zip-a-folder to v3.0.0 should fix this issue.**

**Comment by akosbalasko** [comment]
Hi @lroche ,
oops, thanks for raising this up, I'll upgrade the dep and release a new version asap!

**Comment by akosbalasko** [comment]
@lroche, fixed, thank you!
