### ISSUE TITLE
keepOriginalHtml:true does not work in the latest (windows) version of Yarle

### ISSUE THREAD

**Issue by frankhommers** [akosbalasko/yarle#542]
I have tried al kinds of scenarios but it just doesn't work....

Any suggestions?

**Comment by frankhommers** [comment]
It does work when you include {link-to-original-block}{link-to-original}{end-link-to-original-block}

In the template

**Comment by bumper314** [comment]
I'm having this issue as well.  If I set `keepOriginalHtml: true` in the GUI config, I can see it's set to `true` in the `yarle_20241114_133346.config` that gets saved during the conversion, but then the log shows `"keepOriginalHtml": false,` unless I include `{link-to-original-block}{link-to-original}{end-link-to-original-block}` in the template.  So now I have `{link-to-original-block}` and I can see the path to the .html file in each note, but absolutely zero .html files get created during the export.
