### ISSUE TITLE
FeatureRequest: decrypt encrypted text elements during import .enex

### ISSUE THREAD

**Issue by MichaelHeydukFraba** [akosbalasko/yarle#543]
I have lots of passwords in my Evernote .enex file. All are locally encrypted passwords with the Evernote encrypt-Text-Feature.
It would be great if I could specify a local password in the Import Settings, so that the enex-importer decrypts all encrypted texts.
Thanks a lot.

**Comment by Code-Curious** [comment]
+1, such a feature would be greatly helpful, perhaps a 1 or more inputs to fill in the encryption password(s) and Yarle would try to try each of them when trying to decrypt the content. However, am not sure about the private encryption key Evernote uses, not sure if we can find it anywhere

**Comment by MichaelHeydukFraba** [comment]
Official Information from Evernote can be found here: https://help.evernote.com/hc/en-us/articles/208314128-What-type-of-encryption-does-Evernote-use-
Please keep in mind, that there is an old (RC2) and a new (AES) Way of encryption!

**Comment by akosbalasko** [comment]
Hi @MichaelHeydukFraba , @Code-Curious ,

Decryption is now supported: https://github.com/akosbalasko/yarle/releases/tag/v6.4.0
In the UI you can find a textArea for passwords, type them separated by commas. Whenever Yarle finds an encrypted part, it goes through the list of passwords and tries to decrypt the content. If a correct password is provided, the note content is going to be decrypted.

**Comment by sfranky** [comment]
I've used this successfully in the past when importing my evernote notes to logseq. I tried today, however, for importing to Obsidian, and it doesn't seem to have an effect. The note is encrypted when importing to Obsidian, and i don't see any mention of an attempt to decrypt in the output log.
