### ISSUE TITLE
Note filename

### ISSUE THREAD

**Issue by andymarden** [akosbalasko/yarle#546]
Itt looks like, when I convert to Obsidian md format, each note gets a filename at the top of  the note which is essentially a duplicate of the title but with dodgy characters replaced. Is this a yarle thing and can it be switched off?

**Comment by andymarden** [comment]
SO, in this example of a note called Wetsuit, I get the title of the note 4 times! 3 of them may well be Obsidian's settings by pretty sure the 4th should not be there
![image](https://github.com/akosbalasko/yarle/assets/63465082/b9328833-166f-42df-92c6-4ee52f20345e)

**Comment by akosbalasko** [comment]
Dear @andymarden ,
I think it is the default appearance in Obsidian, however it can be configured in the 
Appearance settings. 

The note title can be hidden from the top of the note by setting "Show inline title" to false, and the tabs can be disabled too, but in this case the tabs will be totally hidden, not just the note names. 

Cheers,
akos
