### ISSUE TITLE
Option "Perform URL Encoding on FileNames And Links" may break links to attachments

### ISSUE THREAD

**Issue by Tokolino** [akosbalasko/yarle#551]
I have an attachment linked to the note with the name `WLAN-Artikel_der_c't,_März_2016.pdf` (which is in the proper resources folder, that is named _filesFromEN in my case). 
When I turn on the mentioned option, then the link in the note gets `![[../_filesFromEN/WLAN-Artikel_der_c't,_M%C3%A4rz_2016.pdf]]`, which does not find the file. When I change the **%C3%A4** back to **ä**, then it works.

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
Thanks for raising this issue up, I fixed it in version 6.0.2.
Cheers,
akos

**Comment by jhuebner79** [comment]
Hi, to me it seems the wrong behaviour is still there in the Mac version 6.0.5. I had set the "Perform URL Encoding on FileNames And Links" option and the file got named

Evernote%20Snapshot%2020190814%20174548.png

whereas the reference to it is

./_resources/whatever.resources/Evernote%2520Snapshot%252020190814%2520174548.png

So it seems the "%25"s are somehow either missing from the filename or are too much in the link. Removing them from the link obviously fixes it.
