### ISSUE TITLE
Attachments picture not linked quite correctly

### ISSUE THREAD

**Issue by Tokolino** [akosbalasko/yarle#559]
Hello,
still working on my export for Obsidian... 
A webclip from page https://notsohumblepie.blogspot.com/2010/04/white-chocolate-caramel-cheesecake.html results in a markdown code like this:
`[![[../_filesFromEN/white_chocolate_caramel_cheesecake5t.jpg|268x400]]](http://1.bp.blogspot.com/_WhPHUKwckUw/S8XoAv8XKWI/AAAAAAAACZY/vppGaLLnBTg/s1600/white_chocolate_caramel_cheesecake5t.JPG)`
Although this results in displaying the image in the note, it does not "count" as a link. When I go to the file `white_chocolate_caramel_cheesecake5t.jpg` Obsidian finds it as being _mentioned_ by the note, but not _linked_.
When I manually change it to
`![http://1.bp.blogspot.com/_WhPHUKwckUw/S8XoAv8XKWI/AAAAAAAACZY/vppGaLLnBTg/s1600/white_chocolate_caramel_cheesecake5t.JPG|268x400](../_filesFromEN/white_chocolate_caramel_cheesecake5t.jpg)`
then everything is fine. 

Let me know if you need it as EN enex!

Regards from Cologne

**Comment by akosbalasko** [comment]
Hi @Tokolino, 
Currently I'm travelling back to home, but hopefully I can fix it around the evening.
Thanks for raising this issue!
akos

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
I released the fix in version [v6.0.4 (release)](https://github.com/akosbalasko/yarle/releases/tag/v6.0.4)

**Comment by Tokolino** [comment]
Hi @akosbalasko,
the fix is not quite right... It now places the size indication after the name of the file, not after the alias text. This results also in not being able to detect the attachment as linked.
So instead of
`[http://1.bp.blogspot.com/_WhPHUKwckUw/S8XoAv8XKWI/AAAAAAAACZY/vppGaLLnBTg/s1600/white_chocolate_caramel_cheesecake5t.JPG](../_filesFromEN/white_chocolate_caramel_cheesecake5t.jpg|268x400)`
(as the current version does) it should be 
`[http://1.bp.blogspot.com/_WhPHUKwckUw/S8XoAv8XKWI/AAAAAAAACZY/vppGaLLnBTg/s1600/white_chocolate_caramel_cheesecake5t.JPG|268x400](../_filesFromEN/white_chocolate_caramel_cheesecake5t.jpg)`

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
Oops, sorry, you're right, I missed to add keepImageSize to add to the test settings. I'll fix it tomorrow.

**Comment by Tokolino** [comment]
Thanks and happy new year!

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
It should work from https://github.com/akosbalasko/yarle/releases/tag/v6.0.5
