### ISSUE TITLE
Newer Obsidian versions with property editor require update to front matter template

### ISSUE THREAD

**Issue by wrgrant** [akosbalasko/yarle#560]
With Obsidian v1.5.3, (or sometime recently) there is a new property editor for the front matter.

The current template linked here:
https://github.com/akosbalasko/yarle/blob/ed6026d796829d87be8bca017bd75d8c2321bba8/sampleTemplate.tmpl#L5

Enters Source URL as:
`Source URL: []({source-url})`

But this imports as invalid syntax. Obsidian seems to just want the raw link now, and it will format it properly.
The fix would be to change that line to:
`Source URL: {source-url}`

Also on line 6
https://github.com/akosbalasko/yarle/blob/ed6026d796829d87be8bca017bd75d8c2321bba8/sampleTemplate.tmpl#L6
 `Tags: ` needs to be changed to `tags: ` (just lowercase the T).

With these fixes, I was able to properly import my notebooks.

**Comment by akosbalasko** [comment]
Hi @wrgrant ,
Thank you for raising this up, I relesad the fix
