### ISSUE TITLE
Linked images with dimensions missing escape character

### ISSUE THREAD

**Issue by Tokolino** [akosbalasko/yarle#564]
Hi @akosbalasko,
another problem found: When you have an image inside a table then you need to escape the | in front of the dimension property with an \, otherwise it gets mixed up with the | of the table markdown.

So, this is correct markup:
```
| Title 1 | Title 2 |
| --- | --- |
| ![A picture\|40](Picture10.jpg) | Cell 4 |
```
and this one (which yarle creates, at least in the note I am just investigating) is not:
```
| Title 1 | Title 2 |
| --- | --- |
| ![A picture|40](Picture10.jpg) | Cell 4 |
```

Kind regards from Germany,
Thorsten

**Comment by akosbalasko** [comment]
fixed in https://github.com/akosbalasko/yarle/releases/tag/v6.0.9
