### ISSUE TITLE
Links not converted?

### ISSUE THREAD

**Issue by JonLaliberte** [akosbalasko/yarle#57]
Testing with v2.9.2 in Evernote I have some bits of text that link to normal https websites, in the output md file the links are missing.

Running using parameters: --include-metadata --outputFormat=ObsidianMD --skip-update-time --skip-creation-time

From Evernote:
<img width="606" alt="Screen Shot 2020-09-30 at 11 27 29 AM" src="https://user-images.githubusercontent.com/5403662/94706276-000acd00-0310-11eb-8468-794992c00184.png">

I've confirmed this link is valid and works.

The output markdown file opened in BBEdit:
<img width="782" alt="Screen Shot 2020-09-30 at 11 28 33 AM" src="https://user-images.githubusercontent.com/5403662/94706403-26306d00-0310-11eb-93a8-6f62573c072d.png">

**Comment by akosbalasko** [comment]
Hi @JonLaliberte , pls remove --outputFormat argument, which sets yarle to convert  links in format of the standard MD.

**Comment by JonLaliberte** [comment]
Hi @akosbalasko, I am using it with Obsidian though...

**Comment by akosbalasko** [comment]
AFAIK Obsidian can interpret standard links as well, so you can use them there.
