### ISSUE TITLE
Empty Cyrillic tags

### ISSUE THREAD

**Issue by dtyugaev** [akosbalasko/yarle#578]
When converting notes from Evernote with Cyrillic tags, the resulting MD files contains empty tags. It looks like this:

---
Created at: 16-07-2015
Last updated at: 16-07-2015
tags: # #
---

English tags work fine!
yarle version 6.3.0

**Comment by akosbalasko** [comment]
Hi @dtyugaev ,
Could you pls send me an example enex file to reproduce the issue? Thanks a lot!

**Comment by dtyugaev** [comment]
[BG.zip](https://github.com/akosbalasko/yarle/files/13894789/BG.zip)

**Comment by akosbalasko** [comment]
Hi @dtyugaev ,
Thanks, sorry, it is fixed : https://github.com/akosbalasko/yarle/releases/tag/v6.3.1

**Comment by dtyugaev** [comment]
Thanks! It got better, but now there is a problem with uppercase Cyrillic letters.

Maybe the code should look something like this.
cleanTag = cleanTag.replace(/[^А-Яа-я0-9_/\\-]/g, '')

**Comment by akosbalasko** [comment]
Hi @dtyugaev ,
Sorry, sorry, my bad, it was late night yesterday. Now I released a fix 6.3.2.
