### ISSUE TITLE
Enex file doesn exist, only exb

### ISSUE THREAD

**Issue by mescalito** [akosbalasko/yarle#58]
Hi!
I have no idea where to find an Enex file
I only can see a `notes.exb` file inside C:\Users\Polaris\Evernote\Databases

any idea?
Thanks

**Comment by mescalito** [comment]
found it!
From Evernote export your notes into an enex file.

Then run the program and you will get a 

```
internal/modules/cjs/loader.js:638
    throw err;
    ^
```

**Comment by akosbalasko** [comment]
Hi @mescalito !

Please provide the whole error log to see what's wrong.

Thank you!

**Comment by mescalito** [comment]
I fixed the issue, It was the node version I had. I was using v10 and it needed v12

**Comment by akosbalasko** [comment]
It's okay, and thanks for the PR you opened, but there is a github Action which runs all the unit tests on Node 10.x.I checked that an the exact version is 10.22.1.

Which was yours, on which the execution failed?

**Comment by mescalito** [comment]
I had 10.17.0 and it wasn't working, then I recloned the project and did all the `npm i` with v12.0.0 and it worked (nvm).

**Comment by akosbalasko** [comment]
thank you @mescalito !
