### ISSUE TITLE
Issue with attachments being saved in different folders according to different notes

### ISSUE THREAD

**Issue by wendx** [akosbalasko/yarle#595]
1、One enex file contains multiple notes, and I hope the attached images are saved in different folders according to the notes. Can this be achieved using yarle?
2、Another question, after the conversion is completed, my image references become like this. Neither obsidian nor typora can be displayed normally. Is there something wrong with my configuration? How should I configure it?
`![[././assets/unknown_filename-83ead839.png\|385x0]]`

Looking forward to your answer, thank you very much！

**Comment by akosbalasko** [comment]
Hi @wendx ,

1. Yes, pls set "haveEnexLevelResources" to false and  "haveGlobalResources": false also.
2. the double ./ at the beginning is suspicious, would mean that the path itself cannot be resolved. could you pls review the resource folder settings and remove "./" ? 

Cheers,
akos

**Comment by wendx** [comment]
Hi @akosbalasko 

Thank you very much for your reply！
1.It has been able to meet my requirements.
2.Viewing the picture in obsidian is correct，but I want to view the pictures correctly in both Typora and Obsidian.Do I need to configure: Other Standard Markdown-based application？Or are there other better configuration options?

**Comment by akosbalasko** [comment]
hi @wendx ,
1: it has been requested: https://github.com/akosbalasko/yarle/issues/102 , but unfortunately still had no time to implement it. If you think that it is really important for you, I could reprioritize my tasks, pls raise it on [issuehunt](https://oss.issuehunt.io/r/akosbalasko/yarle)
2. I have to check which markdown "dialect" is supported by Typora, I'll get back to you.

**Comment by akosbalasko** [comment]
Hi @wendx ,
About 2: yes, select StandardMD instead of Obsidian to make it work on Typora.

**Comment by akosbalasko** [comment]
I think I answered all of your questions, or the feat. request has already been requested by others, so I'd close this issue.

**Comment by wendx** [comment]
Sorry for the late reply。I tried config as "Other Standard Markdown-based application",  but it doesn't seem to work.The image format is still not supported by typora，Below is my configuration information：
`Current config is: {
    "enexSources": [
        "C:\\Users\\wen\\yingxiang\\xxxx.enex"
    ],
    "outputDir": "I:\\cbb2",
    "keepOriginalHtml": false,
    "isMetadataNeeded": true,
    "isNotebookNameNeeded": false,
    "isZettelkastenNeeded": false,
    "useZettelIdAsFilename": false,
    "plainTextNotesOnly": false,
    "skipWebClips": false,
    "useHashTags": true,
    "trimStartingTabs": false,
    "convertPlainHtmlNewlines": false,
    "encryptionPasswords": [
        ""
    ],
    "nestedTags": {
        "separatorInEN": "_",
        "replaceSeparatorWith": "---",
        "replaceSpaceWith": "-"
    },
    "outputFormat": "StandardMD",
    "taskOutputFormat": "StandardMD",
    "obsidianTaskTag": "",
    "urlEncodeFileNamesAndLinks": false,
    "sanitizeResourceNameSpaces": true,
    "replacementChar": "_",
    "replacementCharacterMap": {
        "<": "_",
        ">": "_",
        ":": "_",
        "\"": "_",
        "/": "_",
        "\\": "_",
        "|": "_",
        "?": "_",
        "*": "_"
    },
    "pathSeparator": "/",
    "resourcesDir": "assets",
    "turndownOptions": {
        "headingStyle": "atx"
    },
    "skipLocation": true,
    "skipCreationTime": false,
    "skipUpdateTime": false,
    "skipSourceUrl": false,
    "skipTags": false,
    "skipEnexFileNameFromOutputPath": false,
    "keepMDCharactersOfENNotes": false,
    "monospaceIsCodeBlock": false,
    "currentTemplate": "---\n\n{created-at-block}Created at: {created-at}{end-created-at-block}\n{updated-at-block}Last updated at: {updated-at}{end-updated-at-block}\n{source-url-block}Source URL: {source-url}{end-source-url-block}\n{tags-block}tags: {tags}{end-tags-block}\n\n---\n\n{title-block}# {title}{end-title-block}\n\n\n{content-block}{content}{end-content-block}\n\n",
    "logseqSettings": {
        "journalNotes": false
    },
    "obsidianSettings": {
        "omitLinkDisplayName": false
    },
    "dateFormat": "YYYY-MM-DD",
    "keepImageSize": "ObsidianMD",
    "keepOriginalAmountOfNewlines": false,
    "haveEnexLevelResources": false,
    "haveGlobalResources": false,
    "useUniqueUnknownFileNames": true,
    "useLevenshteinForLinks": false
}`
