### ISSUE TITLE
Feat: Support Typora

### ISSUE THREAD

**Issue by wendx** [akosbalasko/yarle#596]
The image is not in standard markdown format and Typora cannot display it properly.

> ![[./_resources/fpga_debug.resources/unknown_filename-3c5c24cb.png\|881x0]]

I tried config as "Other Standard Markdown-based application", but it doesn't seem to work.The image format is still not supported by typora，Below is my configuration information：
`Current config is: {
    "enexSources": [
        "C:\\Users\\wen\\yingxiang\\work\\Debug.enex"
    ],
    "outputDir": "I:\\ccb",
    "keepOriginalHtml": false,
    "isMetadataNeeded": true,
    "isNotebookNameNeeded": false,
    "isZettelkastenNeeded": false,
    "useZettelIdAsFilename": false,
    "plainTextNotesOnly": false,
    "skipWebClips": false,
    "useHashTags": true,
    "trimStartingTabs": false,
    "convertPlainHtmlNewlines": false,
    "encryptionPasswords": [
        ""
    ],
    "nestedTags": {
        "separatorInEN": "_",
        "replaceSeparatorWith": "---",
        "replaceSpaceWith": "-"
    },
    "outputFormat": "StandardMD",
    "taskOutputFormat": "StandardMD",
    "obsidianTaskTag": "",
    "urlEncodeFileNamesAndLinks": false,
    "sanitizeResourceNameSpaces": true,
    "replacementChar": "_",
    "replacementCharacterMap": {
        "<": "_",
        ">": "_",
        ":": "_",
        "\"": "_",
        "/": "_",
        "\\": "_",
        "|": "_",
        "?": "_",
        "*": "_"
    },
    "pathSeparator": "/",
    "resourcesDir": "_resources",
    "turndownOptions": {
        "headingStyle": "atx"
    },
    "skipLocation": true,
    "skipCreationTime": false,
    "skipUpdateTime": false,
    "skipSourceUrl": false,
    "skipTags": false,
    "skipEnexFileNameFromOutputPath": false,
    "keepMDCharactersOfENNotes": false,
    "monospaceIsCodeBlock": false,
    "currentTemplate": "---\n\n{created-at-block}Created at: {created-at}{end-created-at-block}\n{updated-at-block}Last updated at: {updated-at}{end-updated-at-block}\n{source-url-block}Source URL: {source-url}{end-source-url-block}\n{tags-block}tags: {tags}{end-tags-block}\n\n---\n\n{title-block}# {title}{end-title-block}\n\n\n{content-block}{content}{end-content-block}\n\n",
    "logseqSettings": {
        "journalNotes": false
    },
    "obsidianSettings": {
        "omitLinkDisplayName": false
    },
    "dateFormat": "YYYY-MM-DD",
    "keepImageSize": "ObsidianMD",
    "keepOriginalAmountOfNewlines": false,
    "haveEnexLevelResources": false,
    "haveGlobalResources": false,
    "useUniqueUnknownFileNames": true,
    "useLevenshteinForLinks": false
}`

**Comment by akosbalasko** [comment]
@wendx ,
Try to set ```keepImageSize``` to Standard too.
Hope it helps.

**Comment by wendx** [comment]
The syntax is correct, but some pictures still cannot be displayed normally. Maybe it is because the picture size parameter is included：“ =588x”? Reference is as follows:
> ![](./_resources/debug.resources/unknown_filename-5d317e03.png =588x)

**Comment by akosbalasko** [comment]
Then pls set KeepImageSize to false.

**Comment by wendx** [comment]
I use yarle windows client, I have configured Keep Image size as NO, and the configuration file is: "keepImageSize":"StandardMD". How can I configure it to false? The configuration content is referenced as follows:

> {"enexSources":["C:\\Users\\wen\\yingxiang\\work\\debug.enex"],"outputDir":"I:\\cbaa","isMetadataNeeded":true,"isNotebookNameNeeded":false,"isZettelkastenNeeded":false,"useZettelIdAsFilename":false,"plainTextNotesOnly":false,"skipLocation":true,"skipCreationTime":true,"skipUpdateTime":true,"skipSourceUrl":true,"skipWebClips":false,"skipTags":true,"useHashTags":true,"outputFormat":"StandardMD","taskOutputFormat":"StandardMD","skipEnexFileNameFromOutputPath":false,"keepMDCharactersOfENNotes":false,"monospaceIsCodeBlock":false,"keepOriginalHtml":false,"currentTemplate":"---\n\n{created-at-block}Created at: {created-at}{end-created-at-block}\n{updated-at-block}Last updated at: {updated-at}{end-updated-at-block}\n{source-url-block}Source URL: {source-url}{end-source-url-block}\n{tags-block}tags: {tags}{end-tags-block}\n\n---\n\n{title-block}# {title}{end-title-block}\n\n\n{content-block}{content}{end-content-block}\n\n","resourcesDir":"_resources","trimStartingTabs":false,"convertPlainHtmlNewlines":false,"encryptionPasswords":[""],"nestedTags":{"separatorInEN":"_","replaceSeparatorWith":"---","replaceSpaceWith":"-"},"logseqSettings":{"journalNotes":false},"obsidianSettings":{"omitLinkDisplayName":false},"dateFormat":"YYYY-MM-DD","keepImageSize":"StandardMD","keepOriginalAmountOfNewlines":false,"urlEncodeFileNamesAndLinks":false,"haveEnexLevelResources":false,"haveGlobalResources":false,"useUniqueUnknownFileNames":true,"useLevenshteinForLinks":false,"sanitizeResourceNameSpaces":true,"replacementChar":"_","replacementCharacterMap":{"<":"_",">":"_",":":"_","\"":"_","/":"_","\\":"_","|":"_","?":"_","*":"_"}}

**Comment by akosbalasko** [comment]
Then it means that Typora cannot recognize imagesizes. As that app was never among the supported target applications, I think it is not a bug, but a feature, so I rename the title and add the propery labels.

**Comment by akosbalasko** [comment]
HI @wendx ,
I released a feature to enable/disable imagesize keeping in links. So I think Typora should work well from now. 

About the feautre: We have two properties from now, keepImageSize is a true/false boolean, to specify whether to keep the sizes or not, while imageSizeFormat specifies the format like Obsidian or Standard, if keepImageSize is set to true.
(feat: https://github.com/akosbalasko/yarle/issues/611)
