### ISSUE TITLE
Image sizes show up even when "keepImageSize":"StandardMD"

### ISSUE THREAD

**Issue by VeraStray** [akosbalasko/yarle#601]
Converting from .enex to standardMD
Fedora/Nobara 38, Gnome, RPM
Try as I might, image sizes (are at least partial image sizes) are showing up in the markdown. 

I have set: 
"taskOutputFormat":"StandardMD"
"keepImageSize":"StandardMD"
"outputFormat":"StandardMD"

I will post full config file below.

Results:
I am getting image links that have sizes in them. Thus linking to the files is broken until I removed the extra size info. 

Example: 
**![](./_resources/filename.522.jpeg =325x171)
![](./_resources/example05.png =180x180)**

Often there is a partial size reference:
**![](./_resources/evernote63348730943318021925677.jpg =4032x)**

CONFIG FILE
`{"enexSources":["/run/media/$removed$/2TB-media/Evernote_BU/Cabinet.enex"],"outputDir":"/run/media/$removed$/2TB-media/EN_Export_Tests/835","isMetadataNeeded":true,"isNotebookNameNeeded":false,"isZettelkastenNeeded":false,"useZettelIdAsFilename":false,"plainTextNotesOnly":false,"skipLocation":true,"skipCreationTime":true,"skipUpdateTime":true,"skipSourceUrl":true,"skipWebClips":false,"skipTags":true,"useHashTags":true,"outputFormat":"StandardMD","taskOutputFormat":"StandardMD","skipEnexFileNameFromOutputPath":true,"keepMDCharactersOfENNotes":false,"monospaceIsCodeBlock":false,"keepOriginalHtml":false,"currentTemplate":"---\n\n{created-at-block}Created at: {created-at}{end-created-at-block}\n{updated-at-block}Last updated at: {updated-at}{end-updated-at-block}\n{source-url-block}Source URL: {source-url}{end-source-url-block}\n{tags-block}tags: {tags}{end-tags-block}\n\n---\n\n{title-block}# {title}{end-title-block}\n\n\n{content-block}{content}{end-content-block}\n\n","resourcesDir":"_resources","trimStartingTabs":false,"convertPlainHtmlNewlines":false,"encryptionPasswords":[""],"nestedTags":{"separatorInEN":"_","replaceSeparatorWith":"---","replaceSpaceWith":"-"},"logseqSettings":{"journalNotes":false},"obsidianSettings":{"omitLinkDisplayName":false},"dateFormat":"YYYY-MM-DD","keepImageSize":"StandardMD","keepOriginalAmountOfNewlines":false,"addExtensionToInternalLinks":true,"urlEncodeFileNamesAndLinks":true,"haveEnexLevelResources":true,"haveGlobalResources":false,"useUniqueUnknownFileNames":false,"useLevenshteinForLinks":false,"sanitizeResourceNameSpaces":true,"replacementChar":"_","replacementCharacterMap":{"<":"_",">":"_",":":"_","\"":"_","/":"_","\\":"_","|":"_","?":"_","*":"_"}}`

**Comment by akosbalasko** [comment]
Hi @VeraStray ,
Thanks for reporting this, it is mentioned in https://github.com/akosbalasko/yarle/issues/596, I'll fix it soon.

**Comment by akosbalasko** [comment]
HI @VeraStray ,
I released a feature to enable/disable imagesize keeping in links.

We have two properties from now, keepImageSize is a true/false boolean, to specify whether to keep the sizes or not, while imageSizeFormat specifies the format like Obsidian or Standard, if keepImageSize is set to true.
(feat: https://github.com/akosbalasko/yarle/issues/611)

**Comment by VeraStray** [comment]
Thank you @akosbalasko ! I really appreciate that this project exists and can help me escape Evernote. Do you have a way of accepting donations?

**Comment by akosbalasko** [comment]
@VeraStray ,
Great to hear that it helps! And thanks for the coffees! :)
