### ISSUE TITLE
Option NOT to add a size of a picture?

### ISSUE THREAD

**Issue by sbsdevplus** [akosbalasko/yarle#611]
The conversion almost always adds a size string to images, either 
![](web_address/photo.jpg =123x95)
or
![](web_address/photo.jpg|123x95)

Or depending on the sizing in the source it can also be
![](web_address/photo.jpg =123)
or
![](web_address/photo.jpg|123)

Or it could be some other combinations.
However, this size addition after the link address makes a lot of problems in Obsidian. Often images can't be displayed properly. If there is an image inside a table it breaks a table if there is an additional | character, and if it is = character it makes even more problems to display images. Sometimes images are displayed with wrong proportions, and if the size string is removed, and there is only ![](web_address/photo.jpg), an image is displayed properly and in the right size. 

Even bigger problem is that both of these examples break several different plugins because they don't properly recognize any of the above as a proper link. If the additional size string removed it all works properly.

In my experience images always display in exactly the same size with or without that additional size string.

Is it possible to make an option NOT to add image size after the link, and keep links normal, like ![](web_address/photo.jpg), regardless of whether there is a size string in the source Evernote note or not? 
(These are usually web clips, which have additional size parameters, even though images are anyway already in that size.)

**Comment by akosbalasko** [comment]
Hi @sbsdevplus ,
Yeah, good point, I add an option as "Disabled" to keepImageSize property soon, that prevents adding any sizes to the images.

**Comment by akosbalasko** [comment]
released, we have two propertiee from now, keepImageSize is a true/false boolean, to specify to keep the sizes or not, whilr imageSizeFormat specifies the format like Obsidian or Standard, if keepImageSize set to true.
