### ISSUE TITLE
Timestamps of MD files are being set to conversion time

### ISSUE THREAD

**Issue by lawabider** [akosbalasko/yarle#623]
I'm exporting from Evernote 6.25.1.9091 , in Windows.

**Comment by akosbalasko** [comment]
Hi @lawabider , 
There are two options here: I'm not sure that the exported enex file contains the creation timestamp if the export was done using this old version of Evernote. 
The other point would be Windows, because Yarle uses a 3rd party lib to handle creation times dedicatedly for Windows (I mean to be transparent by platform). Which Windows version do you use?

**Comment by lawabider** [comment]
> Which Windows version do you use?
My Windows version is 10.0.22000. 
I think I was wrong about the creation timestamp; it was reset when I copied the files. I should have moved them instead. 
I still don't think that the file modified timestamp matches the note's last updated timestamp. I have been assuming that it's supposed to.

**Comment by ipcjs** [comment]
The PR has fixed the issue: #624

**Comment by lawabider** [comment]
Can someone help me to use npx with github urls? 
This works
`npx -p yarle-evernote-to-md@latest yarle --configFile config.json`

But this attempt failed:
`npx -p github:akosbalasko/yarle@latest yarle --configFile config.json`

**Comment by akosbalasko** [comment]
hi @lawabider 
Why do you want to executed yarle dedicatedly from github? the latest version in npm is what you see here on github, so it should be the same.

**Comment by akosbalasko** [comment]
@ipcjs please check your PR, it fails on Ubuntu and Mac, looks working on Windows only.

**Comment by akosbalasko** [comment]
@lawabider that's a bit more complicated, I mean using an other fork, you'd need to build his fork etc... so I would suggest to wait a bit until his PR is approved and merged, currently we are facing with some platform issues (works on Windows, but do not work on any other OS). I try to resolve it today or at most tomorrow.

**Comment by ipcjs** [comment]
@lawabider I have fixed the test cases

**Comment by akosbalasko** [comment]
@ipcjs thanks for the contribution, merged and released!
