### ISSUE TITLE
Add an option to keep letter case in file names

### ISSUE THREAD

**Issue by Cito** [akosbalasko/yarle#73]
It would be nice (particularly for Obsidian) if file names would keep letter casing. Currently, everything seems to be converted to lower case.

**Comment by finn-matti** [comment]
I think that this should be the standard, even. Converting filenames to lower case as is done in filename-utils [line 46](https://github.com/akosbalasko/yarle/blob/ccdcf9ab0f5f24bc0bb355548de096d3039e79df/src/utils/filename-utils.ts#L46) (and [100](https://github.com/akosbalasko/yarle/blob/ccdcf9ab0f5f24bc0bb355548de096d3039e79df/src/utils/filename-utils.ts#L100) which seems redundant) actually breaks links between markdown files (see #26). The files should have the same name as the title of the note in Evernote - warts and all. At least as long as there is not a more sophisticated mechanism to preserve links AND make filenames "safe" - and even then just changing the case will not be enough to make it [posix compatible](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.bpxa400/bpxug469.htm).

**Comment by akosbalasko** [comment]
implemented in #94

**Comment by Cito** [comment]
Are you sure this is implemented in #94? I see that `normalizeTitle()` still uses `toLowerCase()` and my converted notes all have lower case titles. Also, I don't see any new option to keep letter case in the PR and the README.
