### ISSUE TITLE
Option to link to the original HTML 

### ISSUE THREAD

**Issue by Cito** [akosbalasko/yarle#81]
Even the best conversion to Markdown can never be lossless. Some notes may look ugly or become less readable after conversion, or parts of the text may be lost during conversion for some reason.

To be 100% sure that nothing is lost, and to be able to view the original formatting even without a Evernote client, it would be nice if Yarle could (optionally) add a link to the original HTML for every Markdown note. The original HTML files could be stored in a separate subdirectory, similar to the attachments. This directory could be either created from the enex file by Yarle. But Evernote can also export the notes in a directory with individual HTML files. Yarle will then only need to add the links to the files in this directory.

**Comment by khabaroff** [comment]
Inserting URL of an Evernote note as a tag or additional info would be great also

![](https://pics.khabaroff.com/2020-11-12_15-50-39-eh3p3.png)

**Comment by akosbalasko** [comment]
Hi @Cito , hi @khabaroff !
Makes sense. 

So please correct me if I'm wrong, the feature request would be to 
- have a config parameter named keepAsHtml or something, if it's true, then yarle would keep notes as html as well in a separated sub-folder
- have an other config parameter named linkHtmlSourceInNotes, and if it set to true, it would add a meta-tag pointing to the html file of the original note. 

How does it sound?

**Comment by khabaroff** [comment]
Hi @akosbalasko !

I don't think I need keepAsHtml version, just plain text. I do need linkHtmlSourceInNotes as meta-information like cteated-at and updated-at.

**Comment by Cito** [comment]
@khabaroff I'd also like to have URL support and created a separate issue #98 for this. In the context of this issue, the "source HTML" is the HTML stored in Evernote. It may have been copied from the source URL specified in Evernote. But that URL can actually be altered manually and must not point to the same HTML, or the content could have been changed since then. What I like to keep is the original HTML content of the note in Evernote, not the HTML of the page that the URL points to.

@akosbalasko Yes, that sounds good. I think `keepAsHtml` (or maybe just `keepHtml`) should be *off* by default, and `linkHtmlSourceInNotes` (or `linkToHtml`) should be *on* by default (but of course would be ignored when no HTML is kept).

It seems to make sense to create the HMTML from the `<en-note>` tag in the enex notebook. The special HTML output that Evernote can also export does not seem to provide much added value, it contains more or less the same HTML code. However, it has the `<en-media>` tags converted to `img` tags. Yarle would need to do the same.

The HTML could be stored in the `_resources` directory, as an additional file `name-of-the-note.html`. It should have the `<em-media>` tags replaced with `img` tags pointing to the image resource files that are already created there in the `name-of-the-note.resources` subdirectory, so that these files are reused and not stored twice. This could spare a lot of harddisk space.

**Comment by Cito** [comment]
I have suggested an implementation now in #137.

Note that #140 is an example for data loss that can be prevented by saving an additional, redudant HTML copy of each note.
