### ISSUE TITLE
Lists: starting on level 2 is not converted correctly

### ISSUE THREAD

**Issue by finn-matti** [akosbalasko/yarle#89]
At the moment we don't have a good way to deal with notes like this:

<img width="425" alt="Screenshot 2020-11-01 at 16 31 50" src="https://user-images.githubusercontent.com/56148301/97805599-bf300c00-1c5f-11eb-8d22-f464e5890ec7.png">

This generates enml like this (only the note part here):

```html
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
<en-note>
  <ul>
    <ul>
      <li>
        <div>Level 2</div>
      </li>
    </ul>
  </ul>
  <div>
    <br />
  </div>
</en-note>
```

In theory we should get Markdown that looks like this (note the 8 spaces that signify a level 2 list item):

```md
# test - sublists - double indent

        *   Level 2
```

But we get instead:

```md
# test - sublists - double indent

*   Level 2
```

At the moment this is unavoidable because the sublist fix (see [here](https://github.com/akosbalasko/yarle/blob/a074960345f202e141b1008b9cf8315b111e519d/src/convert-html-to-md.ts#L6)) relies on having a sibling `<li>` next to the sublist `<ul>`/`<ol>`.

In order to make these kinds of lists work we would need to overwrite the turndown rule for list items, I think.

**Comment by akosbalasko** [comment]
as far as I know it has been already solved .
