### ISSUE TITLE
Turndown escapes contents that looks like markdown characters

### ISSUE THREAD

**Issue by finn-matti** [akosbalasko/yarle#95]
Related: #90 

From [the turndown readme](https://github.com/domchristie/turndown#escaping-markdown-characters):

>Turndown uses backslashes (`\`) to escape Markdown characters in the HTML input. This ensures that these characters are not interpreted as Markdown when the output is compiled back to HTML. For example, the contents of `<h1>1. Hello world</h1>` needs to be escaped to `1\. Hello world`, otherwise it will be interpreted as a list item rather than a heading.

I happen to be one EN user who has written markdown symbols into his notes, since inline code and block quotes were not part of the editor. 

I think we should provide an option to the user to not escape symbols that look like markdown at all. I think it should be optional, since the point turndown makes is a valid one. But not escaping repairs internal links with underscores etc. immediately. It also doesn't escape `>` symbols for blockquotes and generally does the right thing - in my case.

A simplistic solution would be to simply do this, when the specific option is set, in turndown-service:

```ts
TurndownService.prototype.escape = ((str: string) => str);
```

And maybe that's enough as a first step. However we might want to instead overwrite the `TurndownService.prototype.process` function and add here those types of elements where we don't want to escape MD symbols:

```js
...
if (node.nodeType === 3) {
      replacement = node.isCode ? node.nodeValue : self.escape(node.nodeValue)
 } ...
```

It would be relatively easy to add here other nodes (like divs that are not wrapped by a header tag) that also shouldn't be escaped.

**Comment by akosbalasko** [comment]
I'm on it, @finn-matti , thx for the investigation!
