### ISSUE TITLE
Allow option to transform tags

### ISSUE THREAD

**Issue by finn-matti** [akosbalasko/yarle#96]
I have a pretty involved nested tags tree in Evernote (the idea was to make a transition from EN easier). Example:

```
04-theorie.00-Begriffe.01-Philosophie.01-Logik
```

However, some Markdown software has different standards for nested tags:

- Bear uses slashes for tags: `04-theorie/00-Begriffe/01-Philosophie/01-Logik`
- Obsidian can use either dashes or underscores to differentiate tags and subtags:
    - Dashes: `04-theorie-00-Begriffe-01-Philosophie-01-Logik`
    - Underscores: `04-theorie_00-Begriffe_01-Philosophie_01-Logik`

In order to fit the needs of people, we might want to offer the option to provide a replacement function that gets applied to each tag, if it is set.

**Comment by akosbalasko** [comment]
Wouldn't be enough if we just make the separator of the nested tags configurable? Like this: 
config.json: 
```javascript
{
  nestedTags: {
          separatorInEN: '.',
          separatorToBeApplied: '/'
}
}
```

**Comment by finn-matti** [comment]
I was thinking that maybe some people would use a transform function on their tags in completely different ways than I have in mind. I am also fairly sure that this separation is not very common. I think people are more likely to have native nested tags in Evernote.

**Comment by nununo** [comment]
> I was thinking that maybe some people would use a transform function on their tags in completely different ways than I have in mind. I am also fairly sure that this separation is not very common. I think people are more likely to have native nested tags in Evernote.

Indeed I use tags like:

- recipe_type
  - side_dish
  - main_course
  - desert
- recipe_source
  - book1
  - book2
  - book3
- recipe_duration
  - 15min
  - 30min
  - 60min

And I wouldn't like to keep this hierarchy in Obsidian. Also, like already mentioned in #19, I would like to have my tags in `frontmatter` without the `#` currently hard coded.

Probably solving this issue will automatically solve #19.

Thanks!

**Comment by akosbalasko** [comment]
Breaking news: Obsidian 0.10.3 supports nested tags!
You can now nest tags with unlimited hierarchies using the syntax `#parent/child/subchild`.

Soo, I think we coud go for it. About providing a function: I'm not sure that an average user of EN could provide a replace function, but i think setting the character used to separate nested tags in EN, and an other one to what it should be replaced is much kore understandable for the common.
