### ISSUE TITLE
Better documentation for templates

### ISSUE THREAD

**Issue by Cito** [akosbalasko/yarle#97]
The new `--template`  option should be listed with the other options in the README, and the description of the option should contain a link ot the separate Templates.md document with detailed explanation which already exists.

Also, it should be possible to get the default template, so one can build a custom template based on that. The documentation shows a  template that is "*similar* to YARLE's default template", but I would like to start with the *exact same* default template so that I don't miss anything.

**Comment by akosbalasko** [comment]
Hi @Cito ! Sure sure, I'm on it.

**Comment by akosbalasko** [comment]
Hi @Cito , I linked the description about templates in Readme, please take a look at it.

**Comment by Cito** [comment]
Good to have the link to the default template. Maybe also link to the Template how-to-file (Templates.md) in the documentation for that option, because not everyone will read the changelog.

**Comment by akosbalasko** [comment]
Sure sure, improved. I had a feeling that I've already done it, but not. :) srry.
